---
title: 4. Logistic regression
subtitle: Written by Margriet Groen (partly adapted from materials developed by the PsyTeachR team a the University of Glasgow)
order: 5
---

All of the models considered up to this point dealt with continuous response variables. Previously we looked at categorical predictors, but what if the response itself is categorical? For instance, whether the participant has made an accurate or inaccurate selection or whether a job candidate gets hired or not. Another common type of data is count data, where values are also discrete. Often with count data, the number of opportunities for something to occur is not well-defined. For instance, the number of speech error in a corpus, the number of turn shifts between speakers in a conversation or the number of visits to the doctor. Logistic regression allows us to model a categorical response variable.  

## Lectures
The lecture material for this week follows the recommended chapters in Winter (2020) -- see under 'Reading' below -- and is presented below:

* [**Logistic regression (~38 min)**](https://estream.lancaster.ac.uk/View.aspx?id=61351~5d~uUTAHJgFLO) 

## Reading

### Barr (2020)
[**Link**](https://psyteachr.github.io/stat-models-v1/generalized-linear-mixed-effects-models.html)

This online textbook provides a useful overview of logistic regression. It does at some point talk about modelling multi-level data and random effects. Don't worry about that for now, those will be covered in the second half of 402. This week we'll focus on 'single-level' data.

### Winter (2020)
[**Link**](https://eu.alma.exlibrisgroup.com/leganto/public/44LAN_INST/citation/83408786230001221?auth=SAML)

**Chapter 12** provides a comprehensive introduction to logistic regression and its implementation in R.

## Pre-lab activities
After having watched the lectures and read the textbook chapters you’ll be in a good position to try these activities. Completing them before you attend your lab session will help you to consolidate your learning and help move through the lab activities more smoothly.

### Pre-lab activity 1: Getting ready
#### Get your files ready
Download the [402_week14_forStudents.zip](files/week14/402_week14_forStudents.zip) file and upload it into a new folder in RStudio Server.  

#### Remind yourself of how to access and work with the RStudio Server.

* Sign in to the [**RStudio Server**](http://psy-rstudio.lancaster.ac.uk/), using the login details provided to you via email. Note that when you are not on campus you need to log into the VPN first (look on [**the portal**](https://portal.lancaster.ac.uk/ask/vpn/) if you need more information about that).
* Create a new folder for this week's work. 
* Upload the zip-file to the folder you have created on the RStudio server. Note you can either upload a single file or a zip-file, not a folder with multiple files.
* I highly recommend using R Projects to structure your workflow. You could create an R project for each week of the module. Have a look at section [**8 Workflow: projects**](https://r4ds.had.co.nz/workflow-projects.html) of **R for Data Science** by Hadley Wickam and Gareth Grolemund for an introduction.

### Pre-lab activity 2: Rainy days
Try running the code mentioned in the online textbook by Barr. If you find it easier, use the **`rainy_days.R` script** (in the '402_week14_forStudents folder you were asked to download in 'Pre-lab activity 1'). It illustrates the point that for discrete data, the variance is often not independent from the mean. In addition, it introduces some very useful R functions: What do the `rep()` function, the `c()` function and the `facet_wrap()` function do? Remember, you can type `?function name()` (e.g., `?rep()`) in the Console to get more information about a function.
Finally, can you add a graph for rainy days in Lancaster?

### Pre-lab activity 3:Gesture perception
Please go through the example described in section 12.6 of the chapter on logistic regression in Bodo Winter’s book (link under ‘Reading’). Read the section and (simultaneously) work through the script (`chapter12_6.R`; in the '402_week14_forStudents folder you were asked to download in 'Pre-lab activity 1'). We’ll be working more with this dataset during the lab, so it is helpful if you get a feel for it now.

## Lab activities
In this lab, you’ll gain understanding of and practice with:

* when and why to apply logistic regression to answer questions in psychological science
* conducting logistic regression in R 
* interpreting the R output of logistic regression 
* reporting results for logistic regression following APA guidelines

### Lab activity 1: More work on gesture perception
The dataset we’ll be working with is described in section 12.6 of the chapter on logistic regression in Bodo Winter’s book (link under ‘Reading’). In the pre-lab activity, we explored the dataset and fitted a first logistic regression model assessing whether participants’ perception of a gesture (expressed as a categorical decision between a ‘shape’ vs. a ‘height’ interpretation of the gesture) was affected by the extent of ‘pinkie curl’. In this lab activity, we’ll be building on that analysis by: 1) Repeating the analysis with a centered pinkie curl variable, and 2) by adding a second predictor: index_curve.

To complete this lab activity, please open the R-script [`402_wk14_labAct1.R`](files/week14/402_wk14_labAct1.R) in R Studio and work your way through it.
All instructions, hints and questions are contained in the script.

## Answers

When you have completed all of the lab content, you may want to check your answers with our completed version of the script for this week. **Remember**, looking at this script (studying/revising it) does not replace the process of working through the lab activities, trying them out for yourself, getting stuck, asking questions, finding solutions, adding your own comments, etc. **Actively engaging** with the material is the way to learn these analysis skills, not by looking at someone else's completed code...

<!-- The answers to the questions and the script containing the code will be available after the lab session has taken place.-->

You can download the R-script that includes the relevant code here: [402_wk14_labAct1_withAnswers.R](files/week14/402_wk14_labAct1_withAnswers.R).
