<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.333">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for Psychologists - 7. Two-Factor Between-Participants ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../PSYC214/Week8.html" rel="next">
<link href="../PSYC214/Week6.html" rel="prev">
<link href="../Images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../PSYC121/index.html" rel="" target="" aria-current="page">
 <span class="menu-text">PSYC121</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC122/index.html" rel="" target="">
 <span class="menu-text">PSYC122</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC214/index.html" rel="" target="">
 <span class="menu-text">PSYC214</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC234/index.html" rel="" target="">
 <span class="menu-text">PSYC234</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC401/index.html" rel="" target="">
 <span class="menu-text">PSYC401</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC402/index.html" rel="" target="">
 <span class="menu-text">PSYC402</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Resources/index.html" rel="" target="">
 <span class="menu-text">Resources</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC214/index.html">PSYC214</a></li><li class="breadcrumb-item"><a href="../PSYC214/Week7.html">7. Two-Factor Between-Participants ANOVA</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to PSYC121</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Data Visualisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Linear Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Linear Model Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Linear Model Part 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC214/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC214</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Revision of One-Factor ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Introduction to Factorial Designs and Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week7.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">7. Two-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Two-Factor Mixed and Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Three-Factor ANOVA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC234/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC234</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week9</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC401/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC401</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Data Manipulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week9</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC402/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC402</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Recap of the linear model and practising data-wrangling in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">More on interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Poisson regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to multilevel data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to linear mixed-effects models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Developing linear mixed-effects models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Generalized Linear Mixed-effects Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Ordinal Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Resources</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a></li>
  <li><a href="#todays-lab-activities" id="toc-todays-lab-activities" class="nav-link" data-scroll-target="#todays-lab-activities">Today’s Lab Activities</a>
  <ul class="collapse">
  <li><a href="#analysing-the-hypothetical-covid-19-vaccination-study-data" id="toc-analysing-the-hypothetical-covid-19-vaccination-study-data" class="nav-link" data-scroll-target="#analysing-the-hypothetical-covid-19-vaccination-study-data">Analysing the Hypothetical COVID-19 Vaccination Study Data</a>
  <ul class="collapse">
  <li><a href="#descriptives-statistics-and-assumption-checks" id="toc-descriptives-statistics-and-assumption-checks" class="nav-link" data-scroll-target="#descriptives-statistics-and-assumption-checks">Descriptives statistics and assumption checks</a></li>
  <li><a href="#running-the-anova" id="toc-running-the-anova" class="nav-link" data-scroll-target="#running-the-anova">Running the ANOVA</a></li>
  <li><a href="#generating-the-simple-main-effects" id="toc-generating-the-simple-main-effects" class="nav-link" data-scroll-target="#generating-the-simple-main-effects">Generating the simple main effects</a></li>
  <li><a href="#how-to-write-up-the-results" id="toc-how-to-write-up-the-results" class="nav-link" data-scroll-target="#how-to-write-up-the-results">How to write up the results</a></li>
  <li><a href="#additional-tasks" id="toc-additional-tasks" class="nav-link" data-scroll-target="#additional-tasks">Additional tasks</a></li>
  <li><a href="#final-remarks" id="toc-final-remarks" class="nav-link" data-scroll-target="#final-remarks">Final remarks</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/M1V0/Statistics_for_PSYC/edit/main/PSYC214/Week7.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/M1V0/Statistics_for_PSYC/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">7. Two-Factor Between-Participants ANOVA</h1>
<p class="subtitle lead">Mark Hurlstone, Richard Philpot</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><br> <br></p>
<blockquote class="blockquote">
<p><em>We must make the best of those things that are in our power, and take the rest as nature gives it.</em> —Epictetus, <em>Discourses</em>, 1.1</p>
</blockquote>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Epictetus.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Epictetus</figcaption>
</figure>
</div>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>In this week’s lecture, we demonstrated the steps involved in performing a two-factor between-participants ANOVA by hand using the simplest possible instance of such a design, namely a 2 <span class="math inline">\(\times\)</span> 2 factorial design. We saw that the analysis entails between 1–2 stages. In the first stage, we perform the ANOVA to establish whether either of the two main effects or interaction is significant. If the interaction is not significant, then the analysis stops here. However, if there is a significant interaction, then we must proceed to a second stage and perform a simple main effects analysis to establish the nature of the significant interaction. In today’s lab session, we will demonstrate how to perform a 2 <span class="math inline">\(\times\)</span> 2 between-participants factorial ANOVA in R, including the calculation of the simple main effects. We will also demonstrate how to write up the results of a factorial ANOVA.</p>
<!-- **Note: today, and in future lab sessions, we will only be demonstrating how to do things that you have not previously done before. From now on, you will be generating your own code for a large portion of the lab exercises. So, it would be a good idea to have the lab class materials from previous weeks readily accessible to remind you how to accomplish different tasks.** -->
<!-- **If you get stuck at any point, be proactive and ask for help from one of the GTAs.** -->
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<p>To get started, we first need to log into the R Studio Server.</p>
<p>You can access Lancaster University’s RStudio Server at http://psy-rstudio.lancaster.ac.uk. At present, you will need to be on campus, or connected to the VPN to access this. <strong>If you do not yet have Eduroam (the university wifi) available on your personal device, please follow the instructions from the PSYC214 Announcement Page https://modules.lancaster.ac.uk/mod/forum/discuss.php?d=388256</strong></p>
<p><img src="images/RStudioSignIn.png" class="img-fluid" style="width:75.0%"></p>
<p>If you are on Eduroam (or VPN if off campus) and have accessed the RStudio Server from the URL above, you will now see a login screen (see above). Please use your normal Lancaster University username (e.g., bloggsj). Your own individual RStudio Server password was sent in an email, prior to the first lab, by Kay Rawlins: email header ‘R Studio Server login details’. Please make sure you have this.</p>
<p>Once you are logged into the server, create a folder for today’s session. Navigate to the bottom right panel and under the <code>Files</code> option select the <code>New Folder</code> option. Name the new folder <code>psyc214_lab_7</code>. <strong>Please ensure that you spell this correctly</strong> otherwise when you set the directory using the command given below it will return an error.</p>
<p>Se we can save this session on the server, click <code>File</code> on the top ribbon and select <code>New project</code>. Next, select existing directory and name the working directory <code>~/psyc214_lab_7</code> before selecting <code>create project</code>.</p>
<p>Finally, open a script for executing today’s coding exercises. Navigate to the top left pane of RStudio, select <code>File</code> –&gt; <code>New File</code> –&gt; <code>R Script</code>. Working from a script will make it easier to edit your code and you will be able to save your work for a later date.</p>
<p><img src="images/RScript.png" class="img-fluid" style="width:75.0%"></p>
<p>Let’s set our working directory:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"~/psyc214_lab_7"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that you have created a folder for today’s session, it’s time to add the Week 7 data file. Head on over to the PSYC214 Moodle page, access the lab folder for Week 7, and download the file <code>COVID19Data.csv</code> to your desktop. Next, in the RStudio Server open your new pscy214_lab_7 folder. When in the new folder, select the <code>Upload</code> tab. This will present a box that will ask where the data is that you want to upload. Click on <code>Browse</code>, find the <code>COVID19Data.csv</code> file on your desktop and click <code>OK</code>.</p>
<p>Before moving on, let’s load the relevant libraries that we will be using in today’s session.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)  <span class="co"># For data storage and manipulation</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyr"</span>)      <span class="co"># For tidy data</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"rstatix"</span>)    <span class="co"># For descriptives statistics, outlier detection etc.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"effectsize"</span>) <span class="co"># For generating effect sizes for the ANOVA and simple main effects</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggpubr"</span>)     <span class="co"># For generating QQ plots</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"phia"</span>)       <span class="co"># For calculating simple main effects</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="todays-lab-activities" class="level1">
<h1>Today’s Lab Activities</h1>
<section id="analysing-the-hypothetical-covid-19-vaccination-study-data" class="level2">
<h2 class="anchored" data-anchor-id="analysing-the-hypothetical-covid-19-vaccination-study-data">Analysing the Hypothetical COVID-19 Vaccination Study Data</h2>
<p>Today, we are going to analyse the hypothetical COVID-19 vaccination study data that we plotted in last week’s lab session. As a reminder, the table below summarises the four different conditions of our 2 <span class="math inline">\(\times\)</span> 2 between-participant study.</p>
<p><img src="images/DataMatrix.png" class="img-fluid" style="width:75.0%"></p>
<p>The data set consists of the following four columns:</p>
<ul>
<li><p><strong>Par:</strong> represents the participant number, which ranges from 1–200, with <span class="math inline">\(N\)</span> = 50 participants in each of the four conditions resulting from the combination of our two factors, described next.</p></li>
<li><p><strong>Fear:</strong> represents whether the participant indicated by the row received (Fear Appeal) or did not receive (No Fear Appeal) the fear appeal.</p></li>
<li><p><strong>Efficacy:</strong> represents whether the participant indicated by the row received (Efficacy Message) or did not receive (No Efficacy Message) the self-efficacy message.</p></li>
<li><p><strong>Likelihood:</strong> represents the vaccination likelihood score of the participant indicated by the row.</p></li>
</ul>
<p>The first thing you need to do is load the data into RStudio. Make sure that you name your data frame as <code>covid19Data</code>. Once you have done this, you need to re-level the factors <code>Fear</code> and <code>Efficacy</code> so that “No Fear Appeal” is the baseline level for the former factor, and “No Efficacy Message” is the baseline level for the latter factor. We showed you how to do this in the Week 6 lab session.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># *** ENTER YOUR OWN CODE HERE IMPORTING THE DATA AND RE-LEVELLING THE FACTORS ***</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you have done the above, type <code>(covid19Data)</code> into the console to view the first 10 rows of the data. We want to check that the columns for <code>Fear</code> and <code>Efficacy</code> have the labels <code>&lt;fct&gt;</code> beneath them. This means that R has stored these variables as factors, which is necessary for us to perform the ANOVA. By default, R will import these variables as characters, in which case the variables would have the labels <code>&lt;chr&gt;</code> beneath them. If that is the case for your data, then you will need to modify this before proceeding further.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 4
     Par Fear           Efficacy            Likelihood
   &lt;dbl&gt; &lt;fct&gt;          &lt;fct&gt;                    &lt;dbl&gt;
 1     1 No Fear Appeal No Efficacy Message          6
 2     2 No Fear Appeal No Efficacy Message          4
 3     3 No Fear Appeal No Efficacy Message          7
 4     4 No Fear Appeal No Efficacy Message          8
 5     5 No Fear Appeal No Efficacy Message          5
 6     6 No Fear Appeal No Efficacy Message          6
 7     7 No Fear Appeal No Efficacy Message          2
 8     8 No Fear Appeal No Efficacy Message          6
 9     9 No Fear Appeal No Efficacy Message          5
10    10 No Fear Appeal No Efficacy Message          3
# … with 190 more rows</code></pre>
</div>
</div>
<section id="descriptives-statistics-and-assumption-checks" class="level3">
<h3 class="anchored" data-anchor-id="descriptives-statistics-and-assumption-checks">Descriptives statistics and assumption checks</h3>
<p>The next step is to generate some descriptive statistics. We want the means, standard deviations, and confidence intervals for our four conditions. You have done this before, so you can generate these descriptive statistics for yourselves. When you invoke the <code>group_by()</code> function, remember to include the variables for both factors, <code>(Fear, Efficacy)</code> with a comma seperating them, as I have done here. Make sure you name your descriptive statistics <code>descriptives</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># *** ENTER YOUR OWN CODE FOR GENERATING THE DESCRIPTIVE STATISTICS ***</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you have written and executed the code in RStudio, type <code>descriptives</code> in the console to view the descriptive statistics, it should yield the following output:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Fear            Efficacy   variable  n mean    sd    ci
1 No Fear Appeal No Efficacy Message Likelihood 50 5.16 2.024 0.575
2 No Fear Appeal    Efficacy Message Likelihood 50 4.66 1.869 0.531
3    Fear Appeal No Efficacy Message Likelihood 50 4.80 1.829 0.520
4    Fear Appeal    Efficacy Message Likelihood 50 7.12 1.769 0.503</code></pre>
</div>
</div>
<p>We won’t linger on these descriptive statistics because we inspected them in last week’s lab session.</p>
<p>The next steps are for us to perform our usual checks to make sure that the data are fit for analysis using ANOVA.</p>
<p>The first check we are going to perform is to establish whether there are any outliers or extreme values in the data set. Again, you have done this on numerous occasions before, so it is over to you to generate your own code to identify if there are any outliers or extreme values. As per when you generated the descriptive statistic, remember we have two factors, so when you invoke <code>group_by()</code> you will need to include the arguments <code>(Fear, Efficacy)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># *** ENTER YOUR OWN CODE FOR CHECKING FOR OUTLIERS AND EXTREME VALUES ***</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you have entered your code correctly, then it should generate the following:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  Fear           Efficacy              Par Likelihood is.outlier is.extreme
  &lt;fct&gt;          &lt;fct&gt;               &lt;dbl&gt;      &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
1 No Fear Appeal No Efficacy Message    28         10 TRUE       FALSE     
2 Fear Appeal    No Efficacy Message   126          0 TRUE       FALSE     </code></pre>
</div>
</div>
<p>There are only two outliers in the data, participant 28 who received the combination of No Fear Appeal/No Efficacy Message and participant 126 who received the combination of Fear Appeal/No Efficacy Message. Fortunately, there are no extreme values in the data, so we are safe to proceed without having to remove or transform any scores.</p>
<p>The next check that we need to undertake is to ensure that the homogeneity of variance assumption has been met. As we have seen in previous lectures and labs, this is an important assumption for single-factor between-participants ANOVA, and the same is true for between-participants factorial ANOVA. Applied to the latter, this assumption states that the variances of the different conditions created through the combination of factors should not differ systematically from one another. For our 2 <span class="math inline">\(\times\)</span> 2 between-participants factorial design, this means that the variances for the four conditions created by the combination of our two factors should be roughly comparable.</p>
<p>We can test whether the data satisfy the homogeneity of variance assumption using Levene’s test, as we have done in previous lab classes. As you are familiar with the code for running Levene’s test, you can write this out for yourself. However, when you invoke Levene’s test using <code>levene_test()</code> you will need to enter <code>(Likelihood ~ Fear * Efficacy)</code> as the arguments. The argument <code>Likelihood</code> is our dependent measure, and the argument <code>Fear * Efficacy</code> tells the function that we want to run the test on the four conditions created through the combination of our two factors (that’s what the <code>*</code> is for; note you can also substitute the <code>*</code> with <code>:</code> which has the same meaning and yields the same result).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># *** ENTER YOUR OWN CODE FOR RUNNING LEVENE'S </span><span class="al">TEST</span><span class="co"> ***</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you have entered your code correctly, then it should return the following output:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    df1   df2 statistic     p
  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
1     3   196     0.231 0.875</code></pre>
</div>
</div>
<p>The test result is nonsignificant (<em>p</em> = .875), which indicates that the variances of the four conditions do not differ appreciably from one another. Accordingly, based on Levene’s criterion, we can be satisfied that the homogeneity of variance assumption has been satisfied.</p>
<p>The next check we need to perform is to ensure that our data satisfy the normality assumption. We can do this by running a Shapiro Wilk test on the data for each of our four conditions to determine if the distribution of scores in each differs significantly from a normal distribution. Remember the rule for using this test—if there is less than <span class="math inline">\(N\)</span> = 50 observations per condition, the Shapiro Wilk test is likely to yield an accurate test result, whereas if it is equal to or greater than this number, we are better off inspecting the QQ plots. Our sample size per condition is right on the threshold, so we will use both approaches to testing the normality assumption.</p>
<p>You have executed this test many times before, so once more it’s over to you to generate the code. Just remember once again that when invoking the function <code>group_by</code> you need to supply the arguments <code>(Fear,Efficacy)</code> given that we have two factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># *** ENTER YOUR OWN CODE FOR RUNNING THE SHAPIRO WILK </span><span class="al">TEST</span><span class="co"> ***</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you have executed your code correct, then you should see the following output:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  Fear           Efficacy            variable   statistic       p
  &lt;fct&gt;          &lt;fct&gt;               &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt;
1 No Fear Appeal No Efficacy Message Likelihood     0.936 0.00971
2 No Fear Appeal Efficacy Message    Likelihood     0.958 0.0752 
3 Fear Appeal    No Efficacy Message Likelihood     0.956 0.0587 
4 Fear Appeal    Efficacy Message    Likelihood     0.949 0.0313 </code></pre>
</div>
</div>
<p>Two of the test results are nonsignificant, indicating that the distributions of scores in the No Fear Appeal/Efficacy Message condition and Fear Appeal/No Efficacy Message condition do not differ significantly from a normal distribution (<em>p</em> = .075 and <span class="math inline">\(p\)</span> = .059, respectively). However, the other two test results are significant, indicating that the distributions of scores in the No Fear Appeal/No Efficacy Message condition and Fear Appeal/Efficacy Message condition do differ significantly from a normal distribution (<em>p</em> = .010 and <span class="math inline">\(p\)</span> = .031, respectively).</p>
<p>Let’s not panic just yet. Remember, we are right on the threshold of accuracy for the Shapiro Wilk test, so we should take a look at the QQ plots before taking action.</p>
<p>I am going to assist with you with this next bit. We generate QQ plots (these have been described previously, most recently in the Week 5 lab session, so I won’t go into the details of what they plot and how to interpret them here again) using the <code>ggqqplot()</code> function. Previously, when you have used this function, you only had a single factor and you would have written something like this: <code>ggqqplot(covid19Data, "Likelihood", facet.by = "Fear")</code>, where <code>Fear</code> in this context is the one and only factor in the study. However, we have two factors in our study, so to get what we want we have to pass through our two factors to <code>facet.by</code> as a vector using <code>c("Fear", "Efficacy")</code>. The complete code is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify covid19Data as the data; "Likelihood" as the dependent measure; and facet.by the "Fear" and "Efficacy" factors to create separate plots for the four different conditions.   </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggqqplot</span>(covid19Data, <span class="st">"Likelihood"</span>, <span class="at">facet.by =</span> <span class="fu">c</span>(<span class="st">"Fear"</span>, <span class="st">"Efficacy"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week7_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The QQ plots look very reasonable. The only mildly concerning plot is in the top left-hand corner, which plots the distribution of scores for the No Fear Appeal/No Efficacy Message Condition. Several of the data points at the top end of the scale depart from the diagonal criterion line. I know from experience inspecting these plots that this is not a radical departure, so I’m happy to proceed without taking further action in this instance.</p>
<p>All in all, our data are looking in good shape, so we are ready to perform our ANOVA.</p>
</section>
<section id="running-the-anova" class="level3">
<h3 class="anchored" data-anchor-id="running-the-anova">Running the ANOVA</h3>
<p>To run our ANOVA, we are going to use the <code>aov()</code> function that Richard introduced you to (in your Week 2 lab session) that you used to run a single-factor between-participants ANOVA. We can also use this function to run a between-participants factorial ANOVA.</p>
<p>Let’s suppose, for a moment, that we only had a single factor in our study, Fear. To run the ANOVA we could use: <code>covidModel = aov(data = covid19Data, Likelihood ~ Fear)</code>. Here we are asking R to run an ANOVA in which the data is <code>covid19Data</code> (the first argument), the dependent measure is <code>Likelihood</code> (the second argument), and the factor is <code>Fear</code> (the third argument), and we are storing the results in a variable called <code>covidModel</code> — the value to the left of the <code>=</code> sign. The <code>~</code> sign after <code>Likelihood</code> tells R that we have declared our dependent measure, and what follows after this symbol are the factors for the analysis.</p>
<p>How do we extend this to a two-factor study? Intuitively, you might think we would write something like this: <code>covidModel = aov(data = covid19Data, Likelihood ~ Fear + Efficacy)</code>. Now, after the <code>~</code>, we have added both factors in our study <code>Fear + Efficacy</code> seperated by a <code>+</code> sign. This is part of what we need, but not all that we need. What this code would do is generate the two main effects for Fear and Efficacy, but it would <em>not</em> test the interaction. To test the interaction, we need to modify the code following <code>~</code> as follows: <code>Fear + Efficacy + Fear * Efficacy</code>. The new bit <code>+ Fear * Efficacy</code> tells R that we want to test the interaction as well (that’s what the <code>*</code> between the two factors indicates; we can also use <code>:</code> in place of <code>*</code> which has the same meaning).</p>
<p>The complete piece of code we need to run our ANOVA is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify our ANOVA model (see the main text for details)</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>covidModel <span class="ot">=</span> <span class="fu">aov</span>(<span class="at">data =</span> covid19Data, Likelihood <span class="sc">~</span> Fear <span class="sc">+</span> Efficacy <span class="sc">+</span> Fear <span class="sc">*</span> Efficacy)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This bit prompts R to produce our summary ANOVA table</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(covidModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Fear            1   55.1   55.12   15.68 0.000105 ***
Efficacy        1   41.4   41.40   11.78 0.000732 ***
Fear:Efficacy   1   99.4   99.40   28.27 2.86e-07 ***
Residuals     196  689.2    3.52                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Let’s take a look at the resulting ANOVA table. The first column corresponds to the source of the effect:</p>
<ul>
<li><p><code>Fear</code> corresponds to the main effect of Fear.</p></li>
<li><p><code>Efficacy</code> corresponds to the main effect of Efficacy.</p></li>
<li><p><code>Fear:Efficacy</code> corresponds to the interaction between the two factors.</p></li>
<li><p><code>Residuals</code> corresponds to the error term used to test the above effects.</p></li>
</ul>
<p>The second column gives us the degrees of freedom for each effect indicated by the row (DF), the third column gives us the Sum of Squares (Sum Sq), the fourth column gives us the Mean Square (Mean Sq), the fifth column gives us the <em>F</em> value (F value), and the final column gives us the <em>p</em> value associated with each effect (PR<span class="math inline">\(&gt;\)</span>F). Let’s run some sanity checks, starting with the Mean Square. These values should be equal to the Sum of Squares divided by the degrees of freedom for the effect indicated by the row, which they are (check for yourself). The <em>F</em> values should be equal to the Mean Square divided by the error term (3.52) for the effect indicated by the row, which they are once again (check for yourself).</p>
<p>We can see from the final column that both the main effects and the interaction are significant (all <em>p</em> &lt; .001). To help quantify the size of these effects, let’s get some effect size estimates using the <code>effectsize()</code> function from the effectsize package that we have used previously:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">effectsize</span>(covidModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter     | Eta2 (partial) |       95% CI
---------------------------------------------
Fear          |           0.07 | [0.03, 1.00]
Efficacy      |           0.06 | [0.02, 1.00]
Fear:Efficacy |           0.13 | [0.06, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>The <span class="math inline">\(\eta^2\)</span> effect size estimates for the main effect of fear, efficacy, and the interaction are, .07, .06, and .13, respectively, corresponding to medium-, medium-, and large-sized effects (reminder: 0.01 = small effect; 0.06 = medium effect; 0.14 = large effect).</p>
<p>Because the two main effects only comprise two levels, these results are easy to interpret as they involve a straightfoward pairwise comparison. Looking at the descriptive statistics we requested earlier, we can see that vaccination likelihood scores are higher in the presence of a fear appeal than in the absence of a fear appeal — this is the significant main effect of fear. We can also see that vaccination likelihood scores are higher in the presence of a self-efficacy message than in the absence of a self-efficacy message — this is the significant main effect of efficacy.</p>
<p>The interaction is less straightforward to interpret. To identify the reason for the interaction between factors, we need to proceed to a second stage of analysis in which we test the simple main effects of each factor.</p>
</section>
<section id="generating-the-simple-main-effects" class="level3">
<h3 class="anchored" data-anchor-id="generating-the-simple-main-effects">Generating the simple main effects</h3>
<p>Remember that the simple main effects break down the main effects into their component parts. That is, we examine the effect of each factor at each level of the other factor. In a 2 <span class="math inline">\(\times\)</span> 2 factorial design, each factor has two simple main effects.</p>
<p>We will start by looking at the two simple main effects of fear:</p>
<ul>
<li><p>We want to know whether there is a significant effect of fear (no fear appeal <span class="math inline">\(vs.\)</span> fear appeal) at the <em>no efficacy message</em> level of the efficacy factor.</p></li>
<li><p>We want to know whether there is a significant effect of fear (no fear appeal <span class="math inline">\(vs.\)</span> fear appeal) at the <em>efficacy message</em> level of the efficacy factor.</p></li>
</ul>
<p>We can test these simple main effects using the <code>testInteractions()</code> function in the phia package (phia stands for Post-Hoc Interaciton Analysis) using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the simple main effects of "Fear" at each level of the "Efficacy"  factor</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>smeFear <span class="ot">=</span> <span class="fu">testInteractions</span>(covidModel, <span class="at">fixed =</span> <span class="st">"Efficacy"</span>, <span class="at">across =</span> <span class="st">"Fear"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>(smeFear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F Test: 
P-value adjustment method: holm
                    Value  Df Sum of Sq       F    Pr(&gt;F)    
No Efficacy Message  0.36   1      3.24  0.9214    0.3383    
   Efficacy Message -2.46   1    151.29 43.0238 9.398e-10 ***
Residuals                 196    689.22                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Let’s clarify what we have just requested in the above code. The first argument we supplied to the function was our ANOVA model, <code>covidModel</code>. Next we specified which simple main effects we wanted to test via two further arguments to the function. Specifically, <code>fixed = "Efficacy</code> tells the function that we want to fix (or hold constant) the level of the factor efficacy, and <code>across = "Fear"</code> tells the function that for each of these levels, we want to compare the difference between the no fear appeal and fear appeal levels of the fear factor. Notice that we have made a specific assignment to a variable called <code>smeFear</code> — the value before the <code>=</code> sign. The reason for that will become clear shortly.</p>
<p>Let’s look at the output that has been produced. It’s basically another ANOVA table with our two simple main effects (No Efficacy Message and Efficacy Message, respectively) and also the error term (Residuals) from the initial ANOVA (remember from the Week 7 lecture that we use the same error term from the initial ANOVA to test the simple main effects — notice that Sum of Squares for Residuals is 689.22, which is the same as in the ANOVA table for our initial analysis).</p>
<p>The first row, shows the simple main effect of fear at the <em>no efficacy message</em> level of the efficacy factor. This simple main effect is nonsignificant (<em>p</em> = .338). Thus, in the absence of a self-efficacy message, the likelihood of vaccinating is unaffected by whether or not a person is a given a fear appeal.</p>
<p>The secod row, shows the simple main effect of fear at the <em>efficacy message</em> level of the efficacy factor. This simple main effect is significant (<em>p</em> &lt; .001). Looking at the descriptive statistics we generated earlier, we can see that this is because in the presence of a self-efficacy message vaccination likelihood scores are higher in the presence than in the absence of a fear appeal.</p>
<p>We can also request effect sizes for these simple main effects using the <code>effectsize()</code> function. This is why we saved our simple main effects to the variable <code>smeFear</code>. This allows us to get the effect sizes using the following bit of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">effectsize</span>(smeFear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter           | Eta2 (partial) |       95% CI
---------------------------------------------------
No Efficacy Message |       4.68e-03 | [0.00, 1.00]
Efficacy Message    |           0.18 | [0.11, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>The effect size for the first simple main effect, which was nonsignificant, is nonsurprisingly very small (<span class="math inline">\(\eta^2\)</span> = .00), whereas the effect size for the second simple main effect, which was significant, is large (<span class="math inline">\(\eta^2\)</span> = .18).</p>
<p>Next, we want to look at the two simple main effects of efficacy:</p>
<ul>
<li><p>We want to know whether there is a significant effect of efficacy (no efficacy message <span class="math inline">\(vs.\)</span> efficacy message) at the <em>no fear appeal</em> level of the fear factor.</p></li>
<li><p>We want to know whether there is a significant effect of efficacy (no efficacy message <span class="math inline">\(vs.\)</span> efficacy message) at the <em>fear appeal</em> level of the fear factor.</p></li>
</ul>
<p>We can get these simple main effects using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the simple main effects of "Efficacy" at each level of the "Fear" factor</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>smeEfficacy <span class="ot">=</span> <span class="fu">testInteractions</span>(covidModel, <span class="at">fixed =</span> <span class="st">"Fear"</span>, <span class="at">across =</span> <span class="st">"Efficacy"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>(smeEfficacy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F Test: 
P-value adjustment method: holm
               Value  Df Sum of Sq       F    Pr(&gt;F)    
No Fear Appeal  0.50   1      6.25  1.7774     0.184    
   Fear Appeal -2.32   1    134.56 38.2661 7.058e-09 ***
Residuals            196    689.22                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This time, to generate the simple main effects of interest we set the second argument to <code>fixed = "Fear</code> which tells the function that we want to fix (or hold constant) the level of the factor fear, and we set the value of the third argument to <code>across = "Fear"</code> which tells the function that for each of those levels, we want to compare the difference between the no efficacy message and efficacy message levels of the efficacy factor. Notice that we have once again made a specific assignment to a variable called <code>smeEfficacy</code> — the value before the <code>=</code> sign, so we can get effect sizes for these simple main effects later.</p>
<p>Let’s once again look at the output that has been produced.</p>
<p>The first row, shows the simple main effect of efficacy at the <em>no fear appeal</em> level of the fear factor. This simple main effect is nonsignificant (<em>p</em> = .184). Thus, in the absence of a fear appeal, the likelihood of vaccinating is unaffected by whether or not a person is given a self-efficacy message.</p>
<p>The secod row, shows the simple main effect of efficacy at the <em>fear appeal</em> level of the fear factor. This simple main effect is significant (<em>p</em> &lt; .001). Looking at the descriptive statistics we generated earlier, we can see that this is because in the presence of a fear appeal vaccination likelihood scores are higher in the presence than in the absence of a self-efficacy message.</p>
<p>We can get the effect sizes of these simple main effects as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">effectsize</span>(smeEfficacy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type I)

Parameter      | Eta2 (partial) |       95% CI
----------------------------------------------
No Fear Appeal |       8.99e-03 | [0.00, 1.00]
Fear Appeal    |           0.16 | [0.09, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>The effect size for the first simple main effect, which was nonsignificant, is nonsurprisingly very small (<span class="math inline">\(\eta^2\)</span> = .01), whereas the effect size for the second simple main effect, which was significant, is large (<span class="math inline">\(\eta^2\)</span> = .16).</p>
</section>
<section id="how-to-write-up-the-results" class="level3">
<h3 class="anchored" data-anchor-id="how-to-write-up-the-results">How to write up the results</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/FearAppealLinePlot.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Figure 1. Vaccination likelihood scores as a function of the fear and efficacy manipulations. Error bars represent 95% confidence intervals.</figcaption>
</figure>
</div>
<p>Figure 1 shows vaccination likelihood scores as a function of the fear and efficacy manipulations. These data were subjected to a 2 (fear: no fear appeal <span class="math inline">\(vs.\)</span> fear appeal) <span class="math inline">\(\times\)</span> 2 (efficacy: no efficacy message <span class="math inline">\(vs.\)</span> efficacy message) between-participants Analysis of Variance. There was a significant main effect of fear, <em>F</em>(1, 196) = 15.68, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .07, with vaccination likelihood scores being higher in the presence than in the absence of a fear appeal, a significant main effect of efficacy, <em>F</em>(1, 196) = 11.78, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .06, with vaccination likelihood scores being higher in the presence than in the absence of a self-efficacy message, and a significant interaction between the two factors, <em>F</em>(1, 196) = 28.27, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .13.</p>
<p>To scrutinise the interaction, a simple main effects analysis was undertaken. In the absence of an efficacy message, there was no significant effect of fear, <em>F</em>(1, 196) = .92, <em>p</em> = .338, <span class="math inline">\(\eta^2\)</span> = .00, whereas in the presence of an efficacy message there was a significant effect of fear, <em>F</em>(1, 196) = 43.02, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .18, with vaccination likelihood scores being higher in the presence than in the absence of a fear appeal. Mirroring these results, in the absence of a fear appeal, there was no significant effect of efficacy, <em>F</em>(1, 196) = 1.78, <em>p</em> = .184, <span class="math inline">\(\eta^2\)</span> = .01, whereas in the presence of a fear appeal there was a significant effect of efficacy, <em>F</em>(1, 196) = 38.27, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .16, with vaccination likelihood scores being higher in the presence than in the absence of an efficacy message.</p>
<p>Hence, people receiving a fear appeal had a higher likelihood of vaccinating against COVID-19 than those that did not receive a fear appeal, but only when the fear appeal was combined with a self-efficacy enhancing message.</p>
</section>
<section id="additional-tasks" class="level3">
<h3 class="anchored" data-anchor-id="additional-tasks">Additional tasks</h3>
<p>The final task is for you to generate the line graph of the data shown in Figure 1 above. This was generated using the code we supplied in last week’s lab session. However, we are now using confidence intervals for the error bars, so you will need to modify this aspect of the code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># *** ENTER YOUR OWN CODE FOR GENERTING THE LINE GRAPH IN FIGURE 1 ***</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
</div>
</section>
<section id="final-remarks" class="level3">
<h3 class="anchored" data-anchor-id="final-remarks">Final remarks</h3>
<p>In this lab session, we have analysed the simplest instance of a two-factor between-participants design—namely a 2 <span class="math inline">\(\times\)</span> 2 design. But what happens if one or both of the factors have more than two levels? In this case, the analysis is a bit more involved. If the main effect of a factor with three or more levels is significant, then we will need to perform follow-up tests (planned comparisons or post-hoc tests), just like we did for a one-factor between-participants ANOVA to interpret the significant main effect. Another implication is that, if the interaction is significant, the simple main effects for any factor with three or more levels will require follow-up tests. Suppose we have a 2 (factor A: Level A<span class="math inline">\(_{1}\)</span> vs.&nbsp;Level A<span class="math inline">\(_{2}\)</span>) <span class="math inline">\(\times\)</span> 3 (factor B: Level B<span class="math inline">\(_{1}\)</span> vs.&nbsp;Level B<span class="math inline">\(_{2}\)</span> vs.&nbsp;Level B<span class="math inline">\(_{3}\)</span>) between participants factorial design. The three simple main effects of factor A will involve only pairwise comparisons (namely A<span class="math inline">\(_{1}\)</span> <em>vs.</em> A<span class="math inline">\(_{2}\)</span>, at levels B<span class="math inline">\(_{1}\)</span>, B<span class="math inline">\(_{2}\)</span>, and B<span class="math inline">\(_{3}\)</span>). However, the two simple main effects of factor B will encompass comparisons between three levels (namely B<span class="math inline">\(_{1}\)</span> <em>vs.</em> B<span class="math inline">\(_{2}\)</span> <em>vs</em> B<span class="math inline">\(_{3}\)</span> at levels A<span class="math inline">\(_{1}\)</span> and A<span class="math inline">\(_{2}\)</span>). These latter simple main effects are like running one-factor ANOVA’s on factors with three levels—if the test result is significant, it only tells us that the means differ, but we need to perform follow-up tests to identify the location of those differences. We will consider this issue in more detail in the next lecture and lab class.</p>
<p>For now, well done! We’ll see you again next week.</p>
<p><strong>FYI: at the end of the week I will upload a version of these lab materials to the lab folder that contains the full working code for the analyses.</strong></p>
<p><br> <br></p>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../PSYC214/Week6.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">6. Introduction to Factorial Designs and Interactions</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../PSYC214/Week8.html" class="pagination-link">
        <span class="nav-page-text">8. Two-Factor Mixed and Within-Participants ANOVA</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Website developed by Matthew Ivory</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../Staff/index.html">For Staff</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/M1V0/Statistics_for_PSYC">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>