---
title: Analysing and Interpreting Psychological Data I
subtitle: "Course coordinators: Padraic Monaghan, Rob Davies"
email-obfuscation: javascript

#listing:
#  id: links
#  template: ../links.ejs
#  contents: guide.yml
---

# Welcome

Welcome to this module PSYC401!

First: The [first video](https://modules.lancaster.ac.uk/mod/url/view.php?id=1979429) is a chat between Rob Davies and Padraic Monaghan giving you a bit of an insight into what we'd like you to take from this module and what our philosophy is for teaching.

Second: Please watch the [second video](https://modules.lancaster.ac.uk/mod/panopto/view.php?id=1977256) to give you an outline of how this module works.

Third: Please then watch the [third video](**MAKE VIDEO**) on how to access the software for this module. Basically, what you need to do is in a web browser go to: http://psy-rstudio.lancaster.ac.uk and login with your university account name, and your university account password.

Note that you can only access this website from on campus, or via the University's VPN. For information on connecting to the VPN, see here: https://answers.lancaster.ac.uk/display/ISS/VPN+help

You can then Upload files from your computer for use in this R studio shiny server via the bottom right of the R studio window, and save files back onto your computer for safe keeping via the Export feature, again accessed via More > Export at the bottom right of the R studio window.

Fourth: The [fourth video](https://modules.lancaster.ac.uk/mod/panopto/view.php?id=1977300) shows you how you can change the accessibility and appearance settings for R studio - if you like.

Fifth: try the self-test quiz to see which route through this module is going to be right for you.


# Course Contacts

|             | Email Address                                                  |
|-------------|----------------------------------------------------------------|
| Padraic Monaghan | [p.monaghan\@lancaster.ac.uk](mailto:p.monaghan@lancaster.ac.uk) |
| Rob Davies  | [r.davies\@lancaster.ac.uk](mailto:r.davies@lancaster.ac.uk)     |
|             |                                                                |
