<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.333">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for Psychologists - 2. Multiple regression including categorical predictors</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../PSYC234/Week3.html" rel="next">
<link href="../PSYC234/Week1.html" rel="prev">
<link href="../Images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="../function.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../PSYC121/index.html" rel="" target="" aria-current="page">
 <span class="menu-text">PSYC121</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC122/index.html" rel="" target="">
 <span class="menu-text">PSYC122</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC214/index.html" rel="" target="">
 <span class="menu-text">PSYC214</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC234/index.html" rel="" target="">
 <span class="menu-text">PSYC234</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC401/index.html" rel="" target="">
 <span class="menu-text">PSYC401</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../PSYC402/index.html" rel="" target="">
 <span class="menu-text">PSYC402</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC234/index.html">PSYC234</a></li><li class="breadcrumb-item"><a href="../PSYC234/Week2.html">2. Multiple regression including categorical predictors</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to PSYC121</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Data Visualisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Linear Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Linear Model Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Linear Model Part 3</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC214/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC214</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Measurement, Variance and Inferential Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. One-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Assumptions of ANOVA and Follow-Up Procedures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. One-Factor Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Revision of One-Factor ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Introduction to Factorial Designs and Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Two-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Two-Factor Mixed and Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Three-Factor ANOVA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC234/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC234</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Review of correlation, simple regression and demonstration of multiple regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">2. Multiple regression including categorical predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Multiple regression models that include interactions (moderated variables)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Factor analysis &amp; the binomial test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Wilcoxon rank-sum test and Wilcoxon signed-rank test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Kruskal-Wallis test and Friedman’s ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Binary logistic regression models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Expanding on binary logistic regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC401/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC401</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introducing Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Manipulating data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Drawing graphs from data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Testing nominal data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Testing differences between groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Open data and your research report</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Hypotheses, measurement and associations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Independent study week; data visualisation and making the most of R knowledge</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Predicting behaviour: The linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC401/Week10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Developing the linear model</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC402/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC402</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Recap of the linear model and practising data-wrangling in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Categorical predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. More on interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Poisson regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Introduction to multilevel data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Introduction to linear mixed-effects models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Developing linear mixed-effects models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Introduction to Generalized Linear Mixed-effects Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/Week20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Introduction to Ordinal Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC402/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lecture" id="toc-lecture" class="nav-link active" data-scroll-target="#lecture">Lecture</a>
  <ul class="collapse">
  <li><a href="#part-1-multiple-regression-2-or-more-predictors" id="toc-part-1-multiple-regression-2-or-more-predictors" class="nav-link" data-scroll-target="#part-1-multiple-regression-2-or-more-predictors">Part 1: Multiple Regression: 2 or more predictors</a>
  <ul class="collapse">
  <li><a href="#continuous-predictors" id="toc-continuous-predictors" class="nav-link" data-scroll-target="#continuous-predictors">Continuous predictors:</a></li>
  <li><a href="#continuous-or-categorical-predictors" id="toc-continuous-or-categorical-predictors" class="nav-link" data-scroll-target="#continuous-or-categorical-predictors">Continuous OR categorical predictors</a></li>
  <li><a href="#binary-categorical-variables" id="toc-binary-categorical-variables" class="nav-link" data-scroll-target="#binary-categorical-variables">Binary categorical variables</a></li>
  </ul></li>
  <li><a href="#demonstration-multiple-regression-with-categorical-predictors" id="toc-demonstration-multiple-regression-with-categorical-predictors" class="nav-link" data-scroll-target="#demonstration-multiple-regression-with-categorical-predictors">Demonstration: Multiple regression with categorical predictors</a>
  <ul class="collapse">
  <li><a href="#import-the-data" id="toc-import-the-data" class="nav-link" data-scroll-target="#import-the-data">Import the data</a></li>
  <li><a href="#tidy" id="toc-tidy" class="nav-link" data-scroll-target="#tidy">Tidy</a></li>
  <li><a href="#visualise" id="toc-visualise" class="nav-link" data-scroll-target="#visualise">Visualise</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  </ul></li>
  <li><a href="#part-2-reference-levels-in-the-regression-model" id="toc-part-2-reference-levels-in-the-regression-model" class="nav-link" data-scroll-target="#part-2-reference-levels-in-the-regression-model">Part 2: Reference levels in the regression model</a></li>
  <li><a href="#demonstration-types-of-categorical-contrasts---transformations" id="toc-demonstration-types-of-categorical-contrasts---transformations" class="nav-link" data-scroll-target="#demonstration-types-of-categorical-contrasts---transformations">Demonstration: Types of categorical contrasts - transformations</a>
  <ul class="collapse">
  <li><a href="#sum-coding-schemes" id="toc-sum-coding-schemes" class="nav-link" data-scroll-target="#sum-coding-schemes">Sum Coding Schemes</a></li>
  </ul></li>
  <li><a href="#mean-centering-continuous-predictors" id="toc-mean-centering-continuous-predictors" class="nav-link" data-scroll-target="#mean-centering-continuous-predictors">Mean Centering Continuous Predictors</a></li>
  <li><a href="#demonstration-unbalanced-variables---transforming-binary-categorical-to-numerical-variables-and-centering-them" id="toc-demonstration-unbalanced-variables---transforming-binary-categorical-to-numerical-variables-and-centering-them" class="nav-link" data-scroll-target="#demonstration-unbalanced-variables---transforming-binary-categorical-to-numerical-variables-and-centering-them">Demonstration: Unbalanced variables - transforming binary categorical to numerical variables and centering them</a></li>
  <li><a href="#transformation-via-standardising" id="toc-transformation-via-standardising" class="nav-link" data-scroll-target="#transformation-via-standardising">Transformation via Standardising</a></li>
  <li><a href="#demonstration-standardising-by-two-standard-deviations" id="toc-demonstration-standardising-by-two-standard-deviations" class="nav-link" data-scroll-target="#demonstration-standardising-by-two-standard-deviations">Demonstration: Standardising by Two Standard Deviations</a></li>
  <li><a href="#more-than-two-levels-and-ordered-variables" id="toc-more-than-two-levels-and-ordered-variables" class="nav-link" data-scroll-target="#more-than-two-levels-and-ordered-variables">More than two levels and ordered variables?</a></li>
  </ul></li>
  <li><a href="#lab-task" id="toc-lab-task" class="nav-link" data-scroll-target="#lab-task">Lab Task</a></li>
  <li><a href="#submit-scripts" id="toc-submit-scripts" class="nav-link" data-scroll-target="#submit-scripts">Submit Scripts</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/M1V0/Statistics_for_PSYC/edit/main/PSYC234/Week2.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/M1V0/Statistics_for_PSYC/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2. Multiple regression including categorical predictors</h1>
<p class="subtitle lead">Emma Mills</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="lecture" class="level1">
<h1>Lecture</h1>
<p><a href="https://modules.lancaster.ac.uk/mod/url/view.php?id=2042339">Lecture Link</a></p>
<p>The lecture materials, including and and R files are downloaded from <a href="data/Wk2/Week2_lecture_materials.zip">here</a> as a zip file. You can upload the zip file directly on to the R server and it will populate a new folder with the files and data files automatically.</p>
<section id="part-1-multiple-regression-2-or-more-predictors" class="level2">
<h2 class="anchored" data-anchor-id="part-1-multiple-regression-2-or-more-predictors">Part 1: Multiple Regression: 2 or more predictors</h2>
<section id="continuous-predictors" class="level3">
<h3 class="anchored" data-anchor-id="continuous-predictors">Continuous predictors:</h3>
<ul>
<li><span class="math inline">\(Y = Intercept + predictor_{continuous} + predictor_{categorical} + Error\)</span></li>
<li><span class="math inline">\(Y = b_0 + b_1X_1 + b_2X_2 +𝜀\)</span></li>
</ul>
<p>Interpretation of Intercept term (<span class="math inline">\(b_0\)</span>): Average when all continuous predictors are at 0 and categorical predictors are at their reference level</p>
<p>Interpretation for continuous coefficients: + A one unit increase in <span class="math inline">\(X_1\)</span> gives a change in Y by the amount of <span class="math inline">\(b_1\)</span> + A one unit increase in <span class="math inline">\(X_2\)</span> gives a change in Y by the amount of <span class="math inline">\(b_2\)</span></p>
</section>
<section id="continuous-or-categorical-predictors" class="level3">
<h3 class="anchored" data-anchor-id="continuous-or-categorical-predictors">Continuous OR categorical predictors</h3>
<p><span class="math inline">\(Y = Intercept + predictor_1 + predictor_2 + Error\)</span> <span class="math inline">\(Y = b0 + b_1X_1 + b_2X_2 +𝜀\)</span></p>
<p>Interpretation for continuous coefficients: A one unit increase in <span class="math inline">\(X_1\)</span> gives a change in Y by the amount of <span class="math inline">\(b_1\)</span></p>
<p>Interpretation for categorical coefficients: + A change to another category within <span class="math inline">\(X_2\)</span> gives a change in Y by the amount of <span class="math inline">\(b_2\)</span></p>
</section>
<section id="binary-categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="binary-categorical-variables">Binary categorical variables</h3>
<p>These are predictors with <strong>only</strong> two levels</p>
<table class="table">
<caption>Examples of binary variables</caption>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Level 1</th>
<th>Level 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Accuracy</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Smoker</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Group</td>
<td>Control</td>
<td>Treatment</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Regression models cope with the categorical nature by assigning numbers and creating ‘contrasts’. + Default contrast scheme in R for binary predictors: + 0 to a level 1 + 1 to level 2 + this is known as ‘Dummy coding’ or ‘treatment coding’, and it automatically creates a ‘reference level’ = 0 which is the level that comes first in the alphabet/numerically. The reference level group is estimated in the Intercept coefficient.</p>
<p>You can allow R to automatically set your reference, which is fine for a balanced variable (with equal numbers of participants/stimuli in each level of the variable), but setting a <em>different</em> reference level may make your hypothesis easier to interpret + This may be useful in the context of factors with more than two levels + You can change the reference level by using the relevel() function to manually reorder the levels of your grouping variable</p>
</section>
</section>
<section id="demonstration-multiple-regression-with-categorical-predictors" class="level2">
<h2 class="anchored" data-anchor-id="demonstration-multiple-regression-with-categorical-predictors">Demonstration: Multiple regression with categorical predictors</h2>
<p>In the demonstration sections, you can follow along using the <code>Multiple_Regression_Categorical_Predictors.Rmd</code> file.</p>
<ul>
<li>dummy / treatment coding</li>
<li>sum coding
<ul>
<li>changing the reference level</li>
</ul></li>
<li>centring and standardising</li>
</ul>
<p>Make sure to load in the following libraries to follow along</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PerformanceAnalytics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="model-for-multiple-regression" class="level4">
<h4 class="anchored" data-anchor-id="model-for-multiple-regression">Model for multiple regression</h4>
<p>Keep the model for multiple regression in mind:</p>
<p>You have seen the two predictor regression model equation before:</p>
<p><span class="math display">\[
Y_i = b_0 + b_1 * X_1 + b_2*X_2 + e_i
\]</span> - <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> can be categorical predictors here - there is no different notation between continuous and categorical predictors.</p>
</section>
<section id="import-the-data" class="level3">
<h3 class="anchored" data-anchor-id="import-the-data">Import the data</h3>
<p>The data set is retrieved from https://www.kaggle.com/mirichoi0218/insurance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Wk2/_Week2_lecture_materials/insurance.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Looking at the information on reading the data in, we have three variables that R has detected as character variables: sex, smoker and region. Brilliant - three categorical variables.</p>
<p>We also have three variables that are continuous: age, bmi, children</p>
</section>
<section id="tidy" class="level3">
<h3 class="anchored" data-anchor-id="tidy">Tidy</h3>
<p>Purely for cosmetic reasons, I am going to change the region variable to acronyms of the geographic regions. This is for labeling of plots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use nested ifelse() statements</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"northeast"</span>, <span class="st">"NE"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">ifelse</span>(d<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"northwest"</span>, <span class="st">"NW"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ifelse</span>(d<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"southeast"</span>, <span class="st">"SE"</span>, <span class="st">"SW"</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Very quickly, from the title of the dataset, it looks like several variables are being used as predictors for insurance <code>charges</code>. You can read a little more at the website above if you like.</p>
</section>
<section id="visualise" class="level3">
<h3 class="anchored" data-anchor-id="visualise">Visualise</h3>
<p>Lets visualise the structure of the variables of the data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>p_sex <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(sex), <span class="at">fill =</span> <span class="fu">factor</span>(sex))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>p_smok <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoker), <span class="at">fill =</span> <span class="fu">factor</span>(smoker))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>p_reg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(region), <span class="at">fill =</span> <span class="fu">factor</span>(region))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (so called) continuous variables</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"slateblue"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>p_age_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>p_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>p_child <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(children)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can also look at the relationships between each of the variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chart.Correlation</span>(d[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>)], <span class="at">histogram=</span><span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<p>we’ll just add them all at this point:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sex <span class="sc">+</span> smoker <span class="sc">+</span> region, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sex + smoker + 
    region, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -11938.5      987.8 -12.086  &lt; 2e-16 ***
age            256.9       11.9  21.587  &lt; 2e-16 ***
bmi            339.2       28.6  11.860  &lt; 2e-16 ***
children       475.5      137.8   3.451 0.000577 ***
sexmale       -131.3      332.9  -0.394 0.693348    
smokeryes    23848.5      413.1  57.723  &lt; 2e-16 ***
regionNW      -353.0      476.3  -0.741 0.458769    
regionSE     -1035.0      478.7  -2.162 0.030782 *  
regionSW      -960.0      477.9  -2.009 0.044765 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Lets have a quick look at the output and the coefficient labels column. All of the categorical variables are toward the bottom of the list because we entered them toward the end of the list in the model.</p>
<ul>
<li>the label for <code>sex</code> is <code>sexmale</code>, which tells us that the reference level for the sex variable is female - makes sense since the default is for the first group in the alphabet to be taken as the reference level group.</li>
<li><code>smoker</code> becomes <code>smokeryes</code> to reflect that being a non-smoker is the reference level group.</li>
</ul>
<p>and so on…</p>
</section>
</section>
<section id="part-2-reference-levels-in-the-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="part-2-reference-levels-in-the-regression-model">Part 2: Reference levels in the regression model</h2>
<p>Reference level in dummy coding becomes hidden in the intercept for the categorical predictor. It’s a good idea to write out what your intercept represents before you start to interpret your model. If dummy coding is used, switching from one level of the categorical predictor to the second level is the same as moving along one unit of a continuous predictor. It follows that for a binary categorical predictor, the slope term is giving you the mean difference between the two groups. If sum coding is used, switching from one level of the categorical predictor to the second level is the same as moving along two units of a continuous predictor</p>
<p>Much better choice if you are including interactions in your regression model. Instead of 0 and 1, -1 and +1 are used. Intercept is at 0 – + Like continuous predictors + Categorical predictor is now ‘centred’ (explained later) + This type of contrast can help for interpreting interactions that occur between categorical and continuous predictors</p>
</section>
<section id="demonstration-types-of-categorical-contrasts---transformations" class="level2">
<h2 class="anchored" data-anchor-id="demonstration-types-of-categorical-contrasts---transformations">Demonstration: Types of categorical contrasts - transformations</h2>
<section id="dummy-or-treatment-coding-scheme" class="level4">
<h4 class="anchored" data-anchor-id="dummy-or-treatment-coding-scheme">Dummy or Treatment Coding Scheme</h4>
<p>lets check how the model sees the categorical variables:</p>
<p>at the moment, R sees the variables as character variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,338 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ age     : num [1:1338] 19 18 28 33 32 31 46 37 37 60 ...
 $ sex     : chr [1:1338] "female" "male" "male" "male" ...
 $ bmi     : num [1:1338] 27.9 33.8 33 22.7 28.9 ...
 $ children: num [1:1338] 0 1 3 0 0 0 1 3 2 0 ...
 $ smoker  : chr [1:1338] "yes" "no" "no" "no" ...
 $ region  : chr [1:1338] "SW" "SE" "SE" "NW" ...
 $ charges : num [1:1338] 16885 1726 4449 21984 3867 ...
 - attr(*, "spec")=
  .. cols(
  ..   age = col_double(),
  ..   sex = col_character(),
  ..   bmi = col_double(),
  ..   children = col_double(),
  ..   smoker = col_character(),
  ..   region = col_character(),
  ..   charges = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>To check the type of contrast coding we need convert the variables to factor class:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">factor</span>(sex),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">smoker =</span> <span class="fu">factor</span>(smoker),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">region =</span> <span class="fu">factor</span>(region))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>check that the class has been changed through calling str() once more</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,338 × 7] (S3: tbl_df/tbl/data.frame)
 $ age     : num [1:1338] 19 18 28 33 32 31 46 37 37 60 ...
 $ sex     : Factor w/ 2 levels "female","male": 1 2 2 2 2 1 1 1 2 1 ...
 $ bmi     : num [1:1338] 27.9 33.8 33 22.7 28.9 ...
 $ children: num [1:1338] 0 1 3 0 0 0 1 3 2 0 ...
 $ smoker  : Factor w/ 2 levels "no","yes": 2 1 1 1 1 1 1 1 1 1 ...
 $ region  : Factor w/ 4 levels "NE","NW","SE",..: 4 3 3 2 2 3 3 2 1 2 ...
 $ charges : num [1:1338] 16885 1726 4449 21984 3867 ...</code></pre>
</div>
</div>
<p>Now we use the <code>contrasts()</code> function to see how R views them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>sex) <span class="co"># reference level = female</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       male
female    0
male      1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>smoker) <span class="co"># reference level = non-smoker</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    yes
no    0
yes   1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>region) <span class="co"># reference level = NE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   NW SE SW
NE  0  0  0
NW  1  0  0
SE  0  1  0
SW  0  0  1</code></pre>
</div>
</div>
<p>You can see from the rows that contain the zeroes (female, nonsmoker and northeast) that these reflect the reference levels automatically selected in the first full regression model summary print out above.</p>
<p>As a quick demonstration, you can control the reference level in the dummy coding command: Using the <code>contr.treatment()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>region) <span class="ot">=</span> <span class="fu">contr.treatment</span>(<span class="dv">4</span>, <span class="at">base =</span> <span class="dv">3</span>)) <span class="co"># change ref level to southeast (row 3)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1 2 4
1 1 0 0
2 0 1 0
3 0 0 0
4 0 0 1</code></pre>
</div>
</div>
<p>Look at row three in the output - the row of zeros indicates that this is now the reference level. I’ll change it back before moving forward.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>region) <span class="ot">=</span> <span class="fu">contr.treatment</span>(<span class="dv">4</span>, <span class="at">base =</span> <span class="dv">1</span>)) <span class="co"># change ref level back to northeast (row 1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2 3 4
1 0 0 0
2 1 0 0
3 0 1 0
4 0 0 1</code></pre>
</div>
</div>
<p>Has our model explained all the structured variance? Lets look at diagnostic plots before we go any further:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># display plots in a 2 x 2 panel</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So, we know little about these variables, and we haven’t even looked at the individual coefficients in the summary outputs but we can see that the percentage of variance explained in the <code>charges</code> variable is greater in the 6 predictor model (75%) over the 3 predictor model (12%) but it is clear from the diagnostic plot above that there is still something not explained in the structure of the residuals.</p>
</section>
<section id="sum-coding-schemes" class="level3">
<h3 class="anchored" data-anchor-id="sum-coding-schemes">Sum Coding Schemes</h3>
<p>So, lets think about interactions - introduced in the context of ANOVA last term and thinking about many of the presentations in the 204 module at the end of last term, they are germain to the structure of experimental design whenever groups are included.</p>
<p>What interactions could be plausible here? Just using what we know about medical problems and charges and the variables we have - could there be an interaction between bmi and smoker status? Do lifestyle choices cluster together to effect medical insurance charges? Does the number of children covered by insurance vary systematically by region?</p>
<p>Plausible interactions from the perspective of a layman (me) and I am not going to model them here. But it may inform the choice of contrasting scheme. If we want to interpret interactions between variables later on - either a mix of continuous and categorical or both categorical predictors, it makes sense to use sum coding. Even though we have one categorical variable with four levels, we can still do this.</p>
<p>It’s a good idea to make copies of variables so that your original variables remain intact.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sexsum =</span> sex,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">smokersum =</span> smoker,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">regionsum =</span> region) <span class="co"># copy categorical variables to the same dataset with a suffix to denote sum coding status</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>sexsum) <span class="co"># dummy coded right now</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       male
female    0
male      1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>sexsum) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)) <span class="co"># levels are now 1 and -1 and variable is now centred</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1]
1    1
2   -1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># repeat for the other two variables</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>smokersum) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)) <span class="co"># levels are now 1 and -1 and variable is now centred</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1]
1    1
2   -1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>regionsum) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">4</span>)) <span class="co"># levels are now 1 and -1 but variable is not centred (because this isn't a binary variable)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1] [,2] [,3]
1    1    0    0
2    0    1    0
3    0    0    1
4   -1   -1   -1</code></pre>
</div>
</div>
<p>Lets refit the regression model using this contrast scheme:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sexsum <span class="sc">+</span> smokersum <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sexsum + smokersum + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -666.94     968.64  -0.689 0.491239    
age            256.86      11.90  21.587  &lt; 2e-16 ***
bmi            339.19      28.60  11.860  &lt; 2e-16 ***
children       475.50     137.80   3.451 0.000577 ***
sexsum1         65.66     166.47   0.394 0.693348    
smokersum1  -11924.27     206.58 -57.723  &lt; 2e-16 ***
regionsum1     587.01     293.11   2.003 0.045411 *  
regionsum2     234.05     292.92   0.799 0.424427    
regionsum3    -448.01     291.24  -1.538 0.124219    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The intercept is massively reduced because:</p>
<ul>
<li>the sum coding scheme has swapped the reference levels of the categorical predictors - For the <code>sex</code> and <code>smoker</code> coefficients, they now represent level 1s <code>female</code> and <code>non-smokers</code>.<br>
</li>
<li>the binary categorical variables are now centred. You can see that the estimates are halved from the <code>m6</code> model that uses dummy / treatment contrast coding.</li>
<li>The binary coefficient estimates shows how much a change in Y for level 1 of the coefficient. A minus sign means it is smaller than the intercept term. No minus sign (a positive value) means it is more than the intercept term.</li>
<li>To find how much of a change for level -1 of the coefficient, you simply change the sign of the coefficient.</li>
</ul>
<p>Lets do the math:</p>
<p><span class="math display">\[
Y_i = b_0 + b_1 * X_1 + b_2*X_2 + e_i
\]</span> We are just going to do the maths for the <code>sex</code> variable for each level: <code>female</code> and <code>male</code>. The <code>sex</code> variable is our fourth predictor, so our maths equation looks like this:</p>
<p><span class="math display">\[
Y_i = b_0 + b_4 * X_4
\]</span></p>
<p>We need the:</p>
<ul>
<li><code>intercept</code> term = <span class="math inline">\(b_0\)</span> = (-666.94)</li>
<li>the coefficient value for <code>sexsum1</code> (65.66) from the model output; this is the fourth predictor, so if we had written out our equation for all the predictors, it would be <span class="math inline">\(b_4\)</span> (as above)</li>
<li>we also need the labels for the two levels of the sex predictor: female (1) and male (-1) because we are going to put those in our <span class="math inline">\(X_4\)</span> part of the equation.</li>
</ul>
<p>Here we go:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_Female <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="fl">65.66</span> <span class="sc">*</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -601.28</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_Male <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="fl">65.66</span> <span class="sc">*</span> <span class="sc">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -732.6</code></pre>
</div>
</div>
<p>Lets do the math for the <code>smoker</code> variable:</p>
<p>The <code>smoker</code> variable is our fifth predictor, so our maths equation looks like this:</p>
<p><span class="math display">\[
Y_i = b_0 + b_5 * X_5
\]</span></p>
<p>We need the:</p>
<ul>
<li><code>intercept</code> term = <span class="math inline">\(b_0\)</span> = (-666.94)</li>
<li>the coefficient value for <code>smokersum1</code> (-11924.27) from the model output; this is the fifth predictor, so if we had written out our equation for all the predictors, it would be <span class="math inline">\(b_5\)</span> (as above)</li>
<li>we also need the labels for the two levels of the smoker variable: no (1) and yes (-1) because we are going to put those in our <span class="math inline">\(X_5\)</span> part of the equation.</li>
</ul>
<p>Here we go:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_nonsmoker <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">11924.27</span> <span class="sc">*</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -12591.21</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_smoker <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">11924.27</span> <span class="sc">*</span> <span class="sc">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11257.33</code></pre>
</div>
</div>
<ul>
<li>You can compare the continuous predictor coefficients and see no difference for their coefficients from model m6.</li>
</ul>
<p>The <code>region</code> variable is a little harder to interpret. Remember that the reference level is now the southwest level of the variable and each region coefficient is the difference from the intercept. So if we want to find the value for southwest, we have to take away region 1 2 and 3 from the intercept term.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_SW <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">587.01</span> <span class="sc">*</span> <span class="dv">1</span>) <span class="sc">+</span> (<span class="fl">234.05</span> <span class="sc">*</span> <span class="dv">1</span>) <span class="sc">+</span> (<span class="sc">-</span><span class="fl">448.01</span> <span class="sc">*</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1467.91</code></pre>
</div>
</div>
</section>
</section>
<section id="mean-centering-continuous-predictors" class="level2">
<h2 class="anchored" data-anchor-id="mean-centering-continuous-predictors">Mean Centering Continuous Predictors</h2>
<p>If you have unequal numbers of participants in your groups: + It may be better to transform your categorical variable to a numerical variable (sometimes called an indicator variable)&nbsp; + and mean centre the new variable as if it was a continuous variable + Use ifelse() function <code>ifelse(d$sex == "female", 1,0)</code> + Use x_mean &lt;- x– mean(x) on the variable to mean centre <code>d$sex_n - mean(d$sex_n)</code></p>
<p>Remember that the raw intercept term represents the average value when all predictors are at zero, so the coefficients are interpreted as the change in Y for some value (larger than 0) the X predictor</p>
<p>An Intercept like this often doesn’t make sense for the verbal model, i.e.&nbsp;the research questions or our hypotheses. What does an intercept term of 0 years or 0 kgs mean?</p>
<p>If we mean-centre the continuous predictors, the Intercept now represents the average value when all continuous predictors are at their average value</p>
<p>Subtract the mean value of a variable from every observation in that variable + The mean of the variable is then = 0 + All values are ‘centred’ around zero + Some will be below zero, some will be above + The intercept term in your model now represents the intercept at the average for the predictor + The predictors are still in their raw units (e.g.&nbsp;years/kgs) + (learn to do these techniques by hard coding&nbsp;– easy to do and the common function that is used, <code>scale()</code>, doesn’t always play very nicely with some other packages!)</p>
</section>
<section id="demonstration-unbalanced-variables---transforming-binary-categorical-to-numerical-variables-and-centering-them" class="level2">
<h2 class="anchored" data-anchor-id="demonstration-unbalanced-variables---transforming-binary-categorical-to-numerical-variables-and-centering-them">Demonstration: Unbalanced variables - transforming binary categorical to numerical variables and centering them</h2>
<p>Look back at the visualisations of the dataset above. Female and male participants in the sex variable are quite evenly spread. Smoker status, however, is very unbalanced. Gelman (2007) recommends creating a new numeric variable in this case and then mean centring a binary variable in this case. If you use this method, do this across each binary categorical variable for consistency.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>p_sex <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(sex), <span class="at">fill =</span> <span class="fu">factor</span>(sex))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>p_smok <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoker), <span class="at">fill =</span> <span class="fu">factor</span>(smoker))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>p_reg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(region), <span class="at">fill =</span> <span class="fu">factor</span>(region))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (so called) continuous variables</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"slateblue"</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>p_age_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>p_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>p_child <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(children)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>sex_n <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>sex <span class="sc">==</span> <span class="st">"female"</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="co"># if sex = female recode as 1 otherwise as 0 in a new numeric variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Have a look at what the summary of the new variable shows - should be quite symmetric:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>sex_n) <span class="co"># balanced variable - look at the mean value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.4948  1.0000  1.0000 </code></pre>
</div>
</div>
<p>so if we transform it to be centred now, by subtracting the mean from each observation rather than leaving it to R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>sex_c <span class="ot">&lt;-</span> <span class="fu">signif</span>(d<span class="sc">$</span>sex_n <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>sex_n), <span class="dv">3</span>) <span class="co"># round to 3 significant figures for readability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>sex_c) <span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-0.4950000 -0.4950000 -0.4950000 -0.0002317  0.5050000  0.5050000 </code></pre>
</div>
</div>
<p>have a look at the first few values of the variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d<span class="sc">$</span>sex_c, <span class="dv">8</span>) <span class="co"># female was 1 so is the positive numbers; male was zero so is the negative numbers here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.505 -0.495 -0.495 -0.495 -0.495  0.505  0.505  0.505</code></pre>
</div>
</div>
<p>If we do the same for the <code>smoker</code> variable - we saw in the bar chart that this was a very unbalanced variable, however here are the actual numbers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">factor</span>(d<span class="sc">$</span>smoker))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  no  yes 
1064  274 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>smoker_n <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>smoker <span class="sc">==</span> <span class="st">"yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="co"># if smoker = yes recode as 1 otherwise as 0 in a new variable</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>smoker_n) <span class="co"># value is not 0.5 which is would be if the variable was balanced in observations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.2048  0.0000  1.0000 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>smoker_c <span class="ot">&lt;-</span> <span class="fu">signif</span>(d<span class="sc">$</span>smoker_n <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>smoker_n), <span class="dv">3</span>) <span class="co"># round to 3 significant figures for readability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>smoker_c) <span class="co"># yes was coded as 1 so the positive values here are smokers and the negative values are non-smokers</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-0.2050000 -0.2050000 -0.2050000 -0.0002167 -0.2050000  0.7950000 </code></pre>
</div>
</div>
<p>have a look at the first few values of the variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d<span class="sc">$</span>smoker_c, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.795 -0.205 -0.205 -0.205 -0.205 -0.205 -0.205 -0.205</code></pre>
</div>
</div>
<p>Let’s refit the model with these variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_cen <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sex_c <span class="sc">+</span> smoker_c <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sex_c + smoker_c + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -7702.9      963.6  -7.994 2.82e-15 ***
age            256.9       11.9  21.587  &lt; 2e-16 ***
bmi            339.2       28.6  11.860  &lt; 2e-16 ***
children       475.5      137.8   3.451 0.000577 ***
sex_c          131.3      332.9   0.394 0.693348    
smoker_c     23848.5      413.1  57.723  &lt; 2e-16 ***
regionsum1     587.0      293.1   2.003 0.045411 *  
regionsum2     234.1      292.9   0.799 0.424427    
regionsum3    -448.0      291.2  -1.538 0.124219    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>So - we have changes for the categorical variables - they are now “centred” - either automatically by R or we have hand coded, transforming our categorical variables into numeric variables.</p>
<p>For consistency - it would make sense to centre the continuous variables also. While you are learning, it’s a good idea to do it longhand:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new variables to keep the original variables intact:</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_c =</span> age <span class="sc">-</span> <span class="fu">mean</span>(age), <span class="co"># new variable = old variable minus the mean of the old variable</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi_c =</span> bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi),</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">child_c =</span> children <span class="sc">-</span> <span class="fu">mean</span>(children)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can check: redraw the plots to check the axes - Note now that the axes are centred around zero for the continuous predictors. Note also how no information has changed within and between the variables - all relative relationships remain the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>p_sex_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(sex_c), <span class="at">fill =</span> <span class="fu">factor</span>(sex_c))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>p_smok_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoker_c), <span class="at">fill =</span> <span class="fu">factor</span>(smoker_c))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>p_regsum <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(regionsum), <span class="at">fill =</span> <span class="fu">factor</span>(regionsum))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="co"># frequency polygons for (so called) continuous variables</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>p_age_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_c)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>p_bmi_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi_c)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>p_child_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(child_c)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex_c, p_smok_c, p_regsum, p_age_c, p_bmi_c, p_child_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Lets plug the centred continuous variables into the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_cen_all <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_c <span class="sc">+</span> bmi_c <span class="sc">+</span> child_c <span class="sc">+</span> sex_c <span class="sc">+</span> smoker_c <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_c + bmi_c + child_c + sex_c + smoker_c + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13289.1      165.9  80.079  &lt; 2e-16 ***
age_c          256.9       11.9  21.587  &lt; 2e-16 ***
bmi_c          339.2       28.6  11.860  &lt; 2e-16 ***
child_c        475.5      137.8   3.451 0.000577 ***
sex_c          131.3      332.9   0.394 0.693348    
smoker_c     23848.5      413.1  57.723  &lt; 2e-16 ***
regionsum1     587.0      293.1   2.003 0.045411 *  
regionsum2     234.1      292.9   0.799 0.424427    
regionsum3    -448.0      291.2  -1.538 0.124219    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>You’ll notice that the only change is on the intercept value - because it is now at the average for each predictor, rather than when each predictor is 0…and it makes more sense, right - the intercept is no longer a negative unit value. Although it would be nice to think that people could pay negative insurance charges - what does that mean? That everyone is in debt? That the health treatment costs less than 0?</p>
<p>Create some more variables to store the standardised variables, which we will create next.</p>
<p>Remember to create a standardised variable, we first centre the variable and then divide it by its standard deviation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new variables to store the standardised values</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="co"># these are standardised by dividing by 1 x sd:</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_z1 =</span> (age <span class="sc">-</span> <span class="fu">mean</span>(age)) <span class="sc">/</span> <span class="fu">sd</span>(age), <span class="co"># new variable = centred variable divided by the standard deviation of the centred variable</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi_z1 =</span> (bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi)) <span class="sc">/</span> <span class="fu">sd</span>(bmi),</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">child_z1 =</span> (children <span class="sc">-</span> <span class="fu">mean</span>(children)) <span class="sc">/</span> <span class="fu">sd</span>(children)</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>p_sex_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(sex_c), <span class="at">fill =</span> <span class="fu">factor</span>(sex_c))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>p_smok_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoker_c), <span class="at">fill =</span> <span class="fu">factor</span>(smoker_c))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>p_regsum <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(regionsum), <span class="at">fill =</span> <span class="fu">factor</span>(regionsum))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a><span class="co"># frequency polygons for (so called) continuous variables</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>p_age_z1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_z1)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>p_bmi_z1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi_z1)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>p_child_z1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(child_z1)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex_c, p_smok_c, p_regsum, p_age_z1, p_bmi_z1, p_child_z1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Only the axes have changed once more….the centre is still zero but the units are now in standard deviations.</p>
<p>What happens when we use the standardised variables with the centred binary variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_z <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_z1 <span class="sc">+</span> bmi_z1 <span class="sc">+</span> child_z1 <span class="sc">+</span> sex_c <span class="sc">+</span> smoker_c <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_z1 + bmi_z1 + child_z1 + sex_c + smoker_c + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13289.1      165.9  80.079  &lt; 2e-16 ***
age_z1        3608.8      167.2  21.587  &lt; 2e-16 ***
bmi_z1        2068.5      174.4  11.860  &lt; 2e-16 ***
child_z1       573.2      166.1   3.451 0.000577 ***
sex_c          131.3      332.9   0.394 0.693348    
smoker_c     23848.5      413.2  57.723  &lt; 2e-16 ***
regionsum1     587.0      293.1   2.003 0.045411 *  
regionsum2     234.0      292.9   0.799 0.424427    
regionsum3    -448.0      291.2  -1.538 0.124219    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>No change in the original correlations either:</p>
<p>This line of code charts correlations between columns 18 - 20 of the dataset <code>d</code> - i.e.&nbsp;the standardised varaibles we just made.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chart.Correlation</span>(d[, <span class="fu">c</span>(<span class="dv">18</span><span class="sc">:</span><span class="dv">20</span>)], <span class="at">histogram=</span><span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="transformation-via-standardising" class="level2">
<h2 class="anchored" data-anchor-id="transformation-via-standardising">Transformation via Standardising</h2>
<p>Take your centred variable and divide each observation by one standard deviation of the variable. Interpretation is now a one standard deviation decrease / increase in the predictor is a (part of) standard deviation in the outcome variable. Because all predictors are now measured in standard deviation units, instead of their raw units, you can compare the size of their coefficients. You couldn’t do this before because they were in different units.</p>
<p>Dividing by 2 standard deviations allows you to directly compare the coefficients for continuous and binary predictors.</p>
</section>
<section id="demonstration-standardising-by-two-standard-deviations" class="level2">
<h2 class="anchored" data-anchor-id="demonstration-standardising-by-two-standard-deviations">Demonstration: Standardising by Two Standard Deviations</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new variables to store the standardised values</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="co"># these are standardised by dividing by 1 x sd:</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_z2 =</span> (age <span class="sc">-</span> <span class="fu">mean</span>(age)) <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(age)), <span class="co"># new variable = centred variable divided by the standard deviation of the centred variable</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi_z2 =</span> (bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi)) <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(bmi)),</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">child_z2 =</span> (children <span class="sc">-</span> <span class="fu">mean</span>(children)) <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(children))</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>p_sex_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(sex_c), <span class="at">fill =</span> <span class="fu">factor</span>(sex_c))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>p_smok_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoker_c), <span class="at">fill =</span> <span class="fu">factor</span>(smoker_c))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>p_regsum <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(regionsum), <span class="at">fill =</span> <span class="fu">factor</span>(regionsum))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co"># frequency polygons for (so called) continuous variables</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>p_age_z2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_z2)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>p_bmi_z2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi_z2)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>p_child_z2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(child_z2)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex_c, p_smok_c, p_regsum, p_age_z2, p_bmi_z2, p_child_z2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Only the axes have changed once more….the centre is still zero, the units are now in standard deviations. The correlations remain the same also. I leave it to the interested reader to cut and paste the code from above and visualise columns 21 - 23 to check this for themselves.</p>
<section id="ordered-variables" class="level4">
<h4 class="anchored" data-anchor-id="ordered-variables">Ordered variables</h4>
<p>We’re not quite finished on our contrast journey…</p>
<p>Consider the <code>children</code> variable - so far I have treated it as a continuous variable but it’s definitely ordered: look at the histogram above again. If we factorise the variable, we will better see the categories</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>children) <span class="co"># summary as a continuous predictor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   1.000   1.095   2.000   5.000 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>children_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(d<span class="sc">$</span>children)) <span class="co"># wrap the factorising command within a summary command for speed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0   1   2   3   4   5 
574 324 240 157  25  18 </code></pre>
</div>
</div>
<p>and we can be pretty confident that the step from 0 - 1 and 3 - 4 is the same size unit of an increase in one person so <code>children</code> is the kind of variable that can be treated as continuous - it has a true zero, but it also is discrete….groups representing counts of different numbers of children…so what happens if we treat this as an ordered variable and use the <code>helmert</code> variant of contrast coding:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>children_h <span class="ot">&lt;-</span> <span class="fu">factor</span>(d<span class="sc">$</span>children)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>children_h) <span class="ot">&lt;-</span> <span class="fu">contr.helmert</span>(<span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1] [,2] [,3] [,4] [,5]
1   -1   -1   -1   -1   -1
2    1   -1   -1   -1   -1
3    0    2   -1   -1   -1
4    0    0    3   -1   -1
5    0    0    0    4   -1
6    0    0    0    0    5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># levels(d$children_h) # checking the order of levels in the children_h variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This contrast coding tell us that the first regression coefficient (look at column [ ,1]) will be the comparison between the first two categories of the <code>children</code> variable - 0 children and one-child families. The second regression coefficient (look at column [ ,2]) for the variable will show a comparison between families with two children and families with either 0 or one child and so on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_zh <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_z1 <span class="sc">+</span> bmi_z1 <span class="sc">+</span> children_h <span class="sc">+</span> sex_c <span class="sc">+</span> smoker_c <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_z1 + bmi_z1 + children_h + sex_c + 
    smoker_c + regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11689.4  -2902.6   -943.7   1492.2  30042.7 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13893.35     337.07  41.218  &lt; 2e-16 ***
age_z1       3613.56     167.40  21.587  &lt; 2e-16 ***
bmi_z1       2054.53     174.48  11.775  &lt; 2e-16 ***
children_h1   195.49     210.68   0.928  0.35362    
children_h2   480.10     148.35   3.236  0.00124 ** 
children_h3    72.19     130.47   0.553  0.58017    
children_h4   439.92     245.53   1.792  0.07341 .  
children_h5   -11.94     243.80  -0.049  0.96094    
sex_c         128.16     332.83   0.385  0.70025    
smoker_c    23836.41     414.14  57.557  &lt; 2e-16 ***
regionsum1    591.52     293.16   2.018  0.04382 *  
regionsum2    211.47     293.68   0.720  0.47160    
regionsum3   -441.62     291.54  -1.515  0.13006    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6059 on 1325 degrees of freedom
Multiple R-squared:  0.7519,    Adjusted R-squared:  0.7497 
F-statistic: 334.7 on 12 and 1325 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This <code>children</code> predictor now has an independent coefficient for each level of the categorical variable. Previously, we had entered the <code>children</code> predictor as continuous, and we were getting an even rate of change, which registered as a significant impact on insurance charges.</p>
<p>Now that we have transformed the variable - and respected the structure of the variable data (it was never continuous), out interpretation of the model needs to change somewhat. The rate of change in insurance chargest across the increase in children is not even (480.10 is not the same as 72.19). This is not a linear relationship. The only significantly different change in insurance charges is the change from 0 or 1 child to two child families. Can you think of a reason why a familiy of two children is predicted to pay significantly higher insurance charges than a family of one child?</p>
<p>There is a little more detail in this model than the previous ones - whether it is useful would depend upon the research question, or a better model than the previous ones, we could deduce using formal model comparison techniques - more of that later.</p>
<p>Lets check the residuals once more:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># display plots in a 2 x 2 panel</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6_zh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That structure is still there!</p>
</section>
<section id="interpretation-of-the-model" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-the-model">Interpretation of the model</h4>
<p>Lets reprint the summary to save scrolling but also save the summary to an object so that we can call the values while interpreting and reporting the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>(m6_zh_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_z1 + bmi_z1 + children_h + sex_c + 
    smoker_c + regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11689.4  -2902.6   -943.7   1492.2  30042.7 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13893.35     337.07  41.218  &lt; 2e-16 ***
age_z1       3613.56     167.40  21.587  &lt; 2e-16 ***
bmi_z1       2054.53     174.48  11.775  &lt; 2e-16 ***
children_h1   195.49     210.68   0.928  0.35362    
children_h2   480.10     148.35   3.236  0.00124 ** 
children_h3    72.19     130.47   0.553  0.58017    
children_h4   439.92     245.53   1.792  0.07341 .  
children_h5   -11.94     243.80  -0.049  0.96094    
sex_c         128.16     332.83   0.385  0.70025    
smoker_c    23836.41     414.14  57.557  &lt; 2e-16 ***
regionsum1    591.52     293.16   2.018  0.04382 *  
regionsum2    211.47     293.68   0.720  0.47160    
regionsum3   -441.62     291.54  -1.515  0.13006    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6059 on 1325 degrees of freedom
Multiple R-squared:  0.7519,    Adjusted R-squared:  0.7497 
F-statistic: 334.7 on 12 and 1325 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="a-possible-interpretation-and-reporting" class="level4">
<h4 class="anchored" data-anchor-id="a-possible-interpretation-and-reporting">A possible interpretation and reporting:</h4>
<p>We have modelled a dataset that has several variables that may be informative in the prediction of insurance charges. With no guiding research questions or hypotheses, we have looked at the structure of the variables and entered them all into a multiple regression model. This is a data-driven, exploratory analysis.</p>
<p>Continuous variables have been standardised; gender and smoker status have been coerced to be numerical variables and mean centred. The six levels of the children variable have been given a helmert type contrast to provide detail of which numbers of children are influential.</p>
<p>Without engaging in any sensitivity analysis or outlier analysis, we report a model with a full set of predictors. The model is significant (<span class="math inline">\(F{_(}{_12,_1325}{_)}\)</span> = 334.7, <em>p</em> &lt; 0.001). This set of predictors explains 75.19% of the variance in insurance charges.</p>
<p>The following details the significant predictors in this model. Each value represents a change in the predictor variable of one standard deviation and its impact upon the outcome variable while holding all other variables constant. Because we have standardised the continuous variables this means they are held constant at their average level. The intercept therefore represents non smoking male individuals, with no children, that live in the SW region of the US.</p>
<p>Age shows a positive association with insurance charges, with an increase in approximately $3613.56 for a one standard deviation unit change on the age scale (age: <em>t</em> = 21.59, <em>p</em> &lt; .001). A person’s body mass index (BMI) also shows a positive relationship and increases insurance charges by approximately $2054 with a one standard deviation change in BMI score (<em>t</em> = 11.77, <em>p</em> &lt; .001). The number of dependents included in insurance cover was only significant on insurance charges at the comparison between 0 and 1 child to the two child level of coverage. Having two children increased insurance charges by approximately $480 (<em>t</em> = 3.24, <em>p</em> &lt; .005), compared to the mean levels for 0 and 1 child. Being a woman is positively associated with an increase in insurance charges, raising insurance costs by approximately $128, however this increase is non-significant (<em>t</em> = 0.39, <em>p</em> = .700). Being a smoker is significantly and positively associated with an increase in insurance charges, raising insurance costs by approximately $23,836 (<em>t</em> = 57.56, <em>p</em> &lt; .001). While living in the northeast region of the country also shows a positive association with insurance charges compared to living in the southwest region (reference level), showing an increase of around $591 (<em>t</em> = 2.02, <em>p</em> = 0.044).</p>
<p>We should be cautious with these interpretations as the residuals show that there is unexplained variability and there are a number of observations that are indicated as having high leverage or high influence so further terms and sensitivity analyses are warranted for a fuller understanding.</p>
<section id="plotting-predictions" class="level5">
<h5 class="anchored" data-anchor-id="plotting-predictions">Plotting predictions</h5>
<p>Plotting an individual effect (or lack of it) is very simple if we are not too worried about being pretty. Plus - because we haven’t changed any of the essential information in any of the coding / centring schemes, you can choose how to plot them, based upon the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"age_z1"</span>, m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"bmi_z1"</span>, m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-53-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"children_h"</span>, m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-53-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"sex_c"</span>, m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-53-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"smoker_c"</span>, m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-53-5.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"regionsum"</span>, m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-53-6.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="checking-that-assumptions-of-linear-regression-are-not-violated" class="level5">
<h5 class="anchored" data-anchor-id="checking-that-assumptions-of-linear-regression-are-not-violated">Checking that assumptions of linear regression are not violated</h5>
<p>We can collect some diagnostic measures to help with assumption checking using the <code>augment()</code> function from the <code>broom</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>(m6zh_metrics <span class="ot">&lt;-</span> <span class="fu">augment</span>(m6_zh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,338 × 13
   charges age_z1 bmi_z1 childr…¹  sex_c smoke…² regio…³ .fitted  .resid    .hat
     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1  16885. -1.44  -0.453 0         0.505   0.795 SW       25243. -8358.  0.00967
 2   1726. -1.51   0.509 1        -0.495  -0.205 SE        3309. -1584.  0.00772
 3   4449. -0.798  0.383 3        -0.495  -0.205 SE        6195. -1746.  0.0105 
 4  21984. -0.442 -1.31  0        -0.495  -0.205 NW        3702. 18283.  0.00616
 5   3867. -0.513 -0.292 0        -0.495  -0.205 NW        5525. -1658.  0.00529
 6   3757. -0.584 -0.807 0         0.505  -0.205 SE        3685.    71.9 0.00604
 7   8241.  0.483  0.455 1         0.505  -0.205 SE       10528. -2287.  0.00614
 8   7282. -0.157 -0.479 3         0.505  -0.205 NW        7519.  -238.  0.00947
 9   6406. -0.157 -0.137 2        -0.495  -0.205 NE        9147. -2740.  0.00779
10  28923.  1.48  -0.791 0         0.505  -0.205 NW       11830. 17093.  0.00705
# … with 1,328 more rows, 3 more variables: .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;,
#   .std.resid &lt;dbl&gt;, and abbreviated variable names ¹​children_h, ²​smoker_c,
#   ³​regionsum</code></pre>
</div>
</div>
<p>Columns 1 - 7 are our variables. <code>fitted</code> and <code>residuals</code> are the predicted values of charges and the <code>error</code> values. The final four columns we use below with some explanation.</p>
<p>Every regression model is built upon the following assumptions:</p>
<ol type="1">
<li>The relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is assumed to be linear (additive)</li>
<li>The residual errors are normally distributed</li>
<li>The residuals have constant variance (homoscedasticity)</li>
<li>The residuals are not correlated (assumption of independence)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># display plots in a 2 x 2 panel</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6_zh) <span class="co"># plot diagnostic plots for m6_zh</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Residuals vs Fitted</strong>: “fitted” here means the predicted values. We want the pink line to align pretty closely with the horizontal dashed line. Comparing this plot with that from the simple regression, this plot looks better. Take note of observation 13 - that was also labelled in the simple regression plots.</p>
<p><strong>Normal Q-Q</strong>: If the residual points (open circles) follow the dashed line, you can assume the residuals are normally distributed</p>
<p><strong>Scale-Location</strong>: This is checking for constant variance in the residuals - not much here. A good indication would be a horizontal pink line with equally spread points. Our graph is not good.</p>
<p><strong>Residuals vs Leverage</strong> - are there any points that are having a large influence on the regression results. They will be numbered and you can then inspect them in your data file. Observations that show standardised residuals (see the table above) above 3 would be problematic. As would observations of a hat value above <span class="math inline">\(2(p+1)/n\)</span> where <span class="math inline">\(p\)</span> = is the number of predictors (but see below) and <span class="math inline">\(n\)</span> = is the number of observations</p>
<p>A different way to observe points with high leverage and high influence:</p>
<p>In the previous scripts, we used a formula for calculating hat values and Cook’s Distance values. Now we are modelling both continuous and categorical predictors that can have reference levels or more than two levels etc etc - each of which have their own model coefficient, it gets a little confusing remembering what ‘p’ stands for. So an easier way is to graph your outlier observations:</p>
<p>Graphing Model Hat Values and Observations with High Leverage: This is a larger dataset, so lets get R doing the sorting for us to check if there are any hat values larger than the model threshold:</p>
<ol type="1">
<li>calculating hat value by hand</li>
<li>using the hat value and filter out any observations from the augmented dataset</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coefficients</span>(m6_zh)) <span class="co"># number of parameters estimated by the model</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(d) <span class="co"># number of observations</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1) calulate the hat value</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>(m6zh_hat <span class="ot">&lt;-</span> (<span class="dv">2</span><span class="sc">*</span>(p<span class="sc">+</span><span class="dv">1</span>))<span class="sc">/</span>N)  <span class="co"># model hat value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02092676</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) filter out observations that are above the hat value in the augmented dataset</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>m6zh_hatvalues <span class="ot">&lt;-</span> m6zh_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.hat <span class="sc">&gt;</span> <span class="fl">0.02092676</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Plot them: hat.plot function taken from Kabacoff, (2022), R in Action.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>hat.plot <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) {</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>              p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coefficients</span>(fit))</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>              n <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">fitted</span>(fit))</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">plot</span>(<span class="fu">hatvalues</span>(fit), <span class="at">main=</span><span class="st">"Index Plot of Hat Values"</span>)</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">abline</span>(<span class="at">h=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)<span class="sc">*</span>p<span class="sc">/</span>n, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">identify</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="fu">hatvalues</span>(fit), <span class="fu">names</span>(<span class="fu">hatvalues</span>(fit)))</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>            }</span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hat.plot</span>(m6_zh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>43 of the datapoints above have hat values larger than the model hat threshold value.</p>
<p>Checking for observations that are influential follows a similar pattern: observations that exceed the <em>Cook’s distance</em> value = <span class="math inline">\(4/(n-p-1)\)</span> are likely to have high influence and the regression results may change if you exclude them. In the presence of such observations that exceed Cook’s distance, unless you know the observation are errors, you probably need to estimate the model without the observations and report both sets of results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>(m6zh_Cooks <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span>(N<span class="sc">-</span>p<span class="dv">-1</span>)) <span class="co"># model Cook's distance value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003021148</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>m6zh_Cooksvalues <span class="ot">&lt;-</span> m6zh_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.cooksd <span class="sc">&gt;</span> <span class="fl">0.003021148</span>) </span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure your dataset is in nrow() function</span></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="co"># and your model is before $coefficients and in the plot line</span></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="co"># here it is m6_zh</span></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a><span class="co"># when you are ready to draw the plot</span></span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a><span class="co"># select all three lines at once and press control and enter</span></span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a><span class="co"># or rerun the chunk by pressing the green arrow in the top right hand corner.</span></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span>(<span class="fu">nrow</span>(d)<span class="sc">-</span><span class="fu">length</span>(m6_zh<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6_zh, <span class="at">which=</span><span class="dv">4</span>, <span class="at">cook.levels=</span>cutoff)</span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span>cutoff, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week2_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are 77 observations that appear to be influential within the dataset…So we may need to run a reduced dataset and compare the outputs</p>
<p>But the model building is not complete. It is likely that there are interactions that could be put into the model and age, as a variable, may be nonlinear - how to deal with both of these is for the next lecture.</p>
<p>There are lots of things to do as we run a multiple regression model - both before, while and after building the model, which will be the focus of the future lectures. We need to look at:</p>
<ul>
<li>a model with some significant predictors! - done</li>
<li>correlation matrices - done</li>
<li>centering predictors - done</li>
<li>standardising predictors - done</li>
<li>models with categorical predictors - done &amp; ongoing
<ul>
<li>interpreting models with categorical predictors - done &amp; ongoing</li>
</ul></li>
<li>models with interaction terms</li>
<li>the properties of multicollinearity</li>
<li>choosing between different models</li>
<li>reporting models - ongoing</li>
</ul>
</section>
</section>
</section>
<section id="more-than-two-levels-and-ordered-variables" class="level2">
<h2 class="anchored" data-anchor-id="more-than-two-levels-and-ordered-variables">More than two levels and ordered variables?</h2>
<p>What about categorical variables with more than two levels? + Dummy / treatment coding - each level’s coefficient is the difference between the reference level and that level + Sum coding – each level’s coefficient is the difference of the level from the intercept + In variables with more than one level, To find the value of -1 , you have to calculate the sum of the intercept and all the other levels of the variable.</p>
<p>What about ordered categorical variables? + Ordered outcome variables use ordinal regression model + Ordered predictor variables use “helmert” coding + Each level of the coefficient is the difference between those level or levels below them + To get the value of the nth level in an ordered variable, you add all the other coefficients that come before that level to the intercept.</p>
</section>
</section>
<section id="lab-task" class="level1">
<h1>Lab Task</h1>
<p>In this lab, you will be working with the R script and data stored <a href="data/Wk2/Week2_lab_materials.zip">here</a>, and the accompanying codebook is accessed <a href="data/Wk2/Data_Codebook.pdf">here</a>.</p>
<p>Work through the Week12_R_Script.Rmd file and enter in your own code to arrive at the following model summary and figures.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk2/Model Summary Output.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Model summary</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk2/Visualise_Predictors.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Visualise Predictors</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk2/Visualise_Bivariate_Correlations.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Visualise Correlations</figcaption>
</figure>
</div>
<p><img src="Images/Wk2/Predictor_plot_absences_z1.png" class="img-fluid" alt="Predictor Absence"> <img src="Images/Wk2/Predictor_Plot_health_z1.png" class="img-fluid" alt="Predictor Health"> <img src="Images/Wk2/Predictor_Plot_school_c.png" class="img-fluid" alt="Predictor School"> <img src="Images/Wk2/Predictor_plot_walc_h.png" class="img-fluid" alt="Predictor Walc"> <img src="Images/Wk2/PredictorPlot_sex_c.png" class="img-fluid" alt="Predictor Sex"></p>
</section>
<section id="submit-scripts" class="level1">
<h1>Submit Scripts</h1>
<p>Remember to submit your group scripts if you want to receive and see feedback on your own and other groups’ scripts.</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../PSYC234/Week1.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">1. Review of correlation, simple regression and demonstration of multiple regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../PSYC234/Week3.html" class="pagination-link">
        <span class="nav-page-text">3. Multiple regression models that include interactions (moderated variables)</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Website developed by Matthew Ivory</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/M1V0/Statistics_for_PSYC">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>