{
  "hash": "8bc3c7d4d98519918e5b02cbb9021554",
  "result": {
    "markdown": "---\ntitle: '8. Two-Factor Mixed and Within-Participants ANOVA'\nsubtitle: \"Mark Hurlstone, Richard Philpot\"\norder: 9\n---\n\n\n\n# Lecture\n\nWatch Part 1 [here](https://modules.lancaster.ac.uk/mod/panopto/view.php?id=2019968)\n\nWatch Part 2 [here](https://modules.lancaster.ac.uk/mod/panopto/view.php?id=2019969)\n\nWatch Part 3 [here](https://modules.lancaster.ac.uk/mod/panopto/view.php?id=2019970)\n\nDownload the lecture slides [here](data/Wk8/Two-Factor Mixed and Within-Participants ANOVA HANDOUT.pdf), and [here](data/Wk8/Two-Factor Mixed and Within-Participants ANOVA.pdf) for a larger version.\n\n# Lab\n\n\n\n\n\n\n<br>\n<br>\n\n> *If, at some point in your life, you should come across anything better than justice, truth, self-control, courage---it must be an extraordinary thing indeed.* ---Marcus Aurelius, *The Meditations*\n\n![Marcus Aurelius](images/MarcusAurelius.png){width=50%}\n\n## Learning Objectives\nIn this week's lecture, we considered the procedures involved in performing a two-factor mixed and fully-within participants ANOVA. Using the hypothetical data on the Stroop effect presented in the lecture, in today's lab session we will demonstrate how to analyse such ANOVA designs in R, including the calculation of the simple main effects and follow up procedures for breaking down simple main effects of factors with three or more levels. We will also demonstrate how to write up the results of two-factor mixed and fully within-participants designs. \n\n**If you get stuck at any point, be proactive and ask for help from one of the GTAs.**\n\n## Getting Started\n\n---\ntitle: \"Statistics for Psychologists\"\npage-layout: article\n---\n\nTo log in to the R server, first make sure that you have the VPN switched on, or you will need to be connected to the university network (Eduroam). To set up the VPN, follow ISS' [instructions here](https://portal.lancaster.ac.uk/ask/digital/services/university-it-network/vpn/) or connecting to Eduroam [here](https://portal.lancaster.ac.uk/ask/digital/services/university-it-network/wi-fi/).\n\nWhen you are connected, navigate to [https://psy-rstudio.lancaster.ac.uk](https://psy-rstudio.lancaster.ac.uk), where you will be shown a login screen that looks like the below. Click the option that says \"Sign in with SAML\".\n\n![](/Includes/1LoginSAML.png) <!-- says no image but it's all about the include setup -->\n\nThis will take you through to the University login screen, where you should enter your username (e.g. ivorym) and then your university password. This will then redirect you to the R server where you can start using RStudio!\n\n![](/Includes/2LoginUser.png)\n\n![](/Includes/3LoginPass.png)\n\n::: {.callout-note}\nIf you have already logged in through the university login already, perhaps to get to the portal, then you may not see the username/password screen. When you click login, you will be redirected straight to RStudio. This is because the server shares the login information securely across the university.\n:::\n\n\n\nOnce you are logged into the server, create a folder for today's session. Navigate to the bottom right panel and under the `Files` option select the `New Folder` option. Name the new folder `psyc214_lab_8`. **Please ensure that you spell this correctly** otherwise when you set the directory using the command given below it will return an error.   \n\nSe we can save this session on the server, click `File` on the top ribbon and select `New project`. Next, select existing directory and name the working directory `~/psyc214_lab_8` before selecting `create project`.\n\nFinally, open a script for executing today's coding exercises. Navigate to the top left pane of RStudio, select `File` -> `New File` -> `R Script`. Working from a script will make it easier to edit your code and you will be able to save your work for a later date. \n\n![](images/RScript.png){width=75%}\n\nLet's set our working directory:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"~/psyc214_lab_8\")\n```\n:::\n\n\nNow that you have created a folder for today's session, it’s time to add the Week 8 files. Download the data and files needed for this lab [here](data/wk8/psyc214_Week8.zip) and save to the newly created folder `psyc214_lab_8`.\n\nBefore moving on, let's load the relevant libraries/functions that we will be using in today's session.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")  # For data storage and manipulation\nlibrary(\"tidyr\")      # For tidy data\nlibrary(\"rstatix\")    # For descriptives statistics, outlier detection, running the ANOVAs etc.\nsource(\"simple.R\")    # Custom function for generating the simple main effects\n```\n:::\n\n::: {.cell}\n\n:::\n\n**Note that the custom function `simple.R` that we use to calculate the simple main effects must be present in your directory whenever you seek to use it.**  \n\n# Today's Lab Activities\n\n## Analysing hypothetical data for the mixed-design Stroop experiment\n\nWe begin by analysing the mixed-design Stroop experiment described in the lecture. Recall that in this experiment, a researcher wants to test the hypothesis that response inhibition---the ability to suppress task-irrelevant information---is impaired in patients with schizophrenia. She predicts that if this is true, then a group of patients with schizophrenia will show a larger Stroop effect than a group of healthy controls. Our researcher administers a multi-trial Stroop task to two groups of participants in a 2 (group: healthy *vs.* schizophrenia) $\\times$ 2 (trial type: congruent *vs.* incongruent) mixed design, where group is a between-participants factor and trial type is a within-participants factor. \n\nThe data set contains four columns:\n\n* **Participant:** represents the participant number, which ranges from 1--80, with $N$ = 40 participants in each of the four conditions resulting from the combination of our two factors. \n\n* **Group:** represents whether the participant belongs to the healthy control group (Healthy) or the schizophrenia group (Schizophrenia).\n\n* **Congruent:** represents the mean response time, averaged across trials, for congruent trials in which the colour word and the ink it is presented in are the same.\n\n* **Incongruent:** represents the mean response time, averaged across trials, for incongruent trials in which the colour word and the ink it is presented in are different.\n\n### Import data, set variables as factors, generate descriptive statistics, and perform assumption checks\n\nThe first thing you need to do is load the data into RStudio. Make sure that you name your data frame as `stroopMixed`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# *** ENTER YOUR OWN CODE HERE TO IMPORT THE DATA ***\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 80 × 4\n   Participant Group   Congruent Incongruent\n         <dbl> <chr>       <dbl>       <dbl>\n 1           1 Healthy       586         906\n 2           2 Healthy       608         773\n 3           3 Healthy       609         887\n 4           4 Healthy       621         775\n 5           5 Healthy       642         699\n 6           6 Healthy       593         707\n 7           7 Healthy       616         850\n 8           8 Healthy       721         763\n 9           9 Healthy       631         760\n10          10 Healthy       639         740\n# … with 70 more rows\n```\n:::\n:::\n\n\nThe next thing we need to do is convert the `Participant` variable into a factor. We can do this with the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert \"Participant into factor\nstroopMixed$Participant = factor(stroopMixed$Participant)\n```\n:::\n\n\nOnce you have done this, you need to convert the `Group` variable into a factor. We'll let you do this yourself using your own code:  \n\n::: {.cell}\n\n```{.r .cell-code}\n# *** ENTER YOUR OWN CODE HERE TO CONVERT \"GROUP\" INTO A FACTOR ***\n```\n:::\n\n::: {.cell}\n\n:::\n\n\nThe next thing we need to do is convert our data from wide format into long format. Richard discussed the distinction between these two formats in his Week 4 lab session and we covered it again in our Week 5 lab session. In brief, we need to create a new variable called `TrialType` that contains the different levels of this factor, congruent and incongruent, which are currently located in different columns. We can do this using the following piece of code which users the `gather()` function encountered previously:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert data into long format\nstroopMixedLong = gather(stroopMixed,TrialType,RT,Congruent:Incongruent,factor_key = TRUE)\n```\n:::\n\n\nLet's unpack what this is doing. The first argument to `gather()`, `stroopMixed`, is the name of our current data set in wide format. The second argument tells R we want a new column called `TrialType`. The third argument, `RT`, tells R the name of our dependent variable. The fourth argument tells R to take the columns `Congruent` through to `Incongruent` and combine them into a column labeled `TrialType` (our second argument). The final argument, `factor_key = TRUE`, tells R that we want this new column to be a factor. The results of this transformation are allocated to a new data frame called `stroopMixedLong`. This contains our data in long format and we will be using this version of the data set from henceforth.\n\nNext, we will generate some descriptive statistics (mean, standard deviation, and confidence intervals). You did this for a between-participants factorial design in last week's seminar, so you can once again generate the code for this yourself.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# *** ENTER YOUR OWN CODE HERE TO GENERATE DESCRIPTIVE STATISTICS ***\n```\n:::\n\n\nIf you have executed the code correctly, then you should see the following output:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 7\n  Group         TrialType   variable     n  mean    sd    ci\n  <fct>         <fct>       <fct>    <dbl> <dbl> <dbl> <dbl>\n1 Healthy       Congruent   RT          40  623.  39.9  12.7\n2 Healthy       Incongruent RT          40  770.  51.4  16.4\n3 Schizophrenia Congruent   RT          40  625.  50.8  16.2\n4 Schizophrenia Incongruent RT          40  889.  44.3  14.2\n```\n:::\n:::\n\n\nAt this stage, we would ordinarily perform various checks including identifying possible outliers and checking that our data satisfy the normality assumption. We won't perform those checks today, not because they are not important (they most certainly are!), but rather because we don't have the time to do so. There is one check that we will perform and that is to see if the homogeneity of variance assumption has been violated. In a mixed design like ours, the homogeneity of variance assumption only applies to the between-participants factors, but not the within-participants factors. \n\nOur between-participants factor is `Group` (healthy vs. schizophrenia) but remember that each group receives each level of our within-participants factor `TrialType` (congruent vs. incongruent). So, we need to test whether the variances are equal or not for the healthy and schizophrenia groups for congruent and incongruent trials separately. The following code will generate what we need: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nstroopMixedLong %>% \n  # Organise the output by the \"TrialType\" factor\n  group_by(TrialType) %>%\n  # Generate Levene's test on the \"Group\" factor\n  levene_test(RT ~ Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  TrialType     df1   df2 statistic      p\n  <fct>       <int> <int>     <dbl>  <dbl>\n1 Congruent       1    78     3.95  0.0505\n2 Incongruent     1    78     0.747 0.390 \n```\n:::\n:::\n\n\nLevene's test is non-significant for congruent trials, *p* = .051 (although notice that it is only marginally short of significance), and also for incongruent trials, *p* = .390. So, we can safely assume that the homogeneity of variance assumption has been satisfied. \n\n### Running the mixed ANOVA\n\nTo run our ANOVA, we are going to use the `anova_test` function from the `rstatix` package. **This is the function that I recommend you use for mixed or fully-within participants factorial designs.** The code required to run the ANOVA is given below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the mixed design ANOVA model\nstroopMixedModel = anova_test(data = stroopMixedLong, dv = RT, wid = Participant, between = Group, within = TrialType, detailed = TRUE)\n# Print the model summary\n(stroopMixedModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nANOVA Table (type II tests)\n\n           Effect DFn DFd        SSn      SSd         F         p p<.05   ges\n1     (Intercept)   1  78 84525386.6 136336.6 48358.096 1.06e-110     * 0.996\n2           Group   1  78   147440.3 136336.6    84.353  4.74e-14     * 0.301\n3       TrialType   1  78  1692705.3 205941.9   641.108  2.27e-39     * 0.832\n4 Group:TrialType   1  78   137886.3 205941.9    52.224  2.91e-10     * 0.287\n```\n:::\n:::\n\n\nTo create the model, the first argument we supplied to `anova_test` was the name of our data, `stroopMixedLong`. The second argument we supplied was our dependent variable, `RT`. The third argument we supplied was `Participant`, which is the column containing the individuals/participants identifier. The fourth argument we supplied was our between-participants factor, `Group`. The fourth argument we supplied was our within-participants factor, `TrialType`. \n\nNotice that the resulting ANOVA table is different in format to those given in the lecture. The format given in the lecture follows a standard convention, but `anova_test` frustratingly uses a different format. The main effects of `Group`, `TrialType`, and the `Group:TrialType` interaction are each given on separate rows. The row corresponding to each effect contain the between-group degrees of freedom (DFn), the error degrees of freedom (DFd), the between-group sums of squares (SSn), the error sums of squares (SSd), the $F$ ratio (F), and the *p* (p) value. On the bright side, this organisation makes it easier to locate the correct degrees of freedom when reporting the different outcomes. \n\nLooking at our ANOVA table, we can see that there is a significant main effect Group, *p* $<$ .001. Inspecting our descriptive statistics, we can see that this arose because mean response times are longer for the schizophrenia group than the healthy group. There is also a significant main effect of Trial Type, *p* $<$ .001, which arose because mean response times are longer for incongruent than congruent trials. Finally, there is a significant interaction between the two factors, *p* $<$ .001. We will defer interpretation of this interaction until later, once we have calculated the simple main effects and plotted the data. By the way, you can just ignore the first row of the table with the outcome named \"intercept\".\n\nBefore we calculate the simple main effects, notice that the ANOVA table generated by `anova_test` does not give us the between-group mean squares or the error mean squares that are used to calculate the $F$ ratios. This is a rather silly omission, and I'm not sure why the creators of the `rstatix` package thought it would be wise to exclude these. Now, you don't need these values to interpret and report your ANOVA, but I do need to extract these values, so I can show you which error term is being used to test the different ANOVA outcomes and the simple main effects that we will calculate shortly. \n\nSo, we are going to calculate the mean squares for ourselves. We will first calculate the between-group mean squares. The between-group mean square is simply the between-group sums of squares (SSn) divided by its corresponding degrees of freedom (DFn). We can calculate this as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the between-group mean sum of squares\nmixedMeanSquareBetween = stroopMixedModel$SSn/stroopMixedModel$DFn\n# Exclude the intercept (row 1 of 4) from the results\nmixedMeanSquareBetween[2:4]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  147440.3 1692705.3  137886.3\n```\n:::\n:::\n\n\nThe first value is the between-group mean square for the main effect of Group (147440.3), the second value is the between-group mean square for the main effect of Trial Type (1692705.3), and the third value is the between-group mean square for the interaction (137886.3).\n\nNext, we will calculate the error mean squares. The error mean square is simply the error sums of squares (SSd) divided by its corresponding degrees of freedom (DFd). We can calculate this as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the error mean sum of squares\nmixedMeanSquareError = stroopMixedModel$SSd/stroopMixedModel$DFd\n# Exclude the intercept (row 1 of 4) from the results\nmixedMeanSquareError[2:4]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1747.906 2640.281 2640.281\n```\n:::\n:::\n\n\nThe first value is the error mean square for the main effect of Group (1747.906), the second value is the error mean square for the main effect of Trial Type (2640.281), and the third value is the error mean square for the interaction (2640.281). Recall that in the lecture, we saw that in a mixed design, the error term for the within-participants factor is used to test both the main effect of that factor and any interaction involving that factor. Sure enough, we can see that the error term for testing the main effect of our within-participants factor, Trial Type, is the same as the one used to test the interaction (i.e., 2640.281).\n\nRemember that the $F$ ratio for each outcome is calculated by dividing its between-group mean square by its error mean square. So, let's calculate the $F$ ratios for ourselves and check they align with what has been given to us in our ANOVA table. We can do that with the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate F ratios\nmixedFRatios = mixedMeanSquareBetween/mixedMeanSquareError\n# Print the results, excluding the intercept\n(mixedFRatios[2:4])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  84.35256 641.10811  52.22411\n```\n:::\n:::\n\n\nThe first $F$ ratio is for the main effect of Group (84.353), the second is for the main effect of Trial Type (641.108), and the third is for the interaction (52.224). If you compare these $F$ values with those given in the ANOVA table, you will see that they are identical. \n\n**To be clear, when conducting a mixed ANOVA in the future, you don't need to go through the steps of calculating the mean squares. I have gone through these steps with you because I need to make it clear what error terms we are using to test the different ANOVA outcomes and our simple main effects.** \n\n### Simple main effects analysis\n\nSince the interaction is significant, we need to calculate the simple main effects. Last week, when calculating the simple main effects for a fully-between participants design, we used the `testInteractions()` function in the `phia` package. Unfortunately, this package cannot be used with mixed and fully within-participants designs. Accordingly, I have created a custom function called `simple()` that will compute the simple main effects for you. \n\nRecall from the lecture that for mixed and within-participants factorial designs, we use an approach to calculating the simple main effects known as the **pooled error terms** approach. What this means is that the simple main effects of each factor are calculated using the same error term. However, the error term we use will differ depending on the factor for which we are calculating the simple main effects (contrast this approach with that we used for calculating the simple main effects in a fully between-participants design, where we used the same error term to calculate the simple main effects of all factors).\n\nBefore we can calculate the simple main effects, there are a few things we need to do. First, we need to store our ANOVA table in a dataframe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the mixed ANOVA table\nmixedAnovaTable = get_anova_table(stroopMixedModel)\n```\n:::\n\n\nNext, we need to calculate the cell totals for each of the four conditions and the number of observations (i.e., scores) in each cell:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get cell totals and counts\nmixedCellTotals = stroopMixedLong %>%\n  # Organise the output by the\"Group\" and \"TrialType\" factors\n  group_by(TrialType, Group) %>%\n  # Request cell totals and number of observations (i.e., scores)\n  summarise(sum = sum(RT),n = n())\n  # Print the results\n  (mixedCellTotals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 4\n# Groups:   TrialType [2]\n  TrialType   Group           sum     n\n  <fct>       <fct>         <dbl> <int>\n1 Congruent   Healthy       24919    40\n2 Congruent   Schizophrenia 24999    40\n3 Incongruent Healthy       30799    40\n4 Incongruent Schizophrenia 35576    40\n```\n:::\n:::\n\n\nThen, we need to specify which simple main effects we want to generate. We are first going to calculate the simple main effects of the factor Group at Trial Type. This means, we are going to:\n\n* Test the difference between the healthy and schizophrenia groups for *congruent* trials only.\n* Test the difference between the healthy and schizophrenia groups for *incongruent* trials only.\n\nTo do this, we need to declare Group as the \"fixed\" factor (we are always comparing the healthy and schizophrenia groups) and Group as the \"across\" factor (the comparison between the healthy and schizophrenia groups occurs \"across\" the congruent and incongruent levels of the Trial Type factor): \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create \"fixed\" and \"across\" factors\nfixed  = \"Group\"\nacross = \"TrialType\"\n```\n:::\n\n\nTo get the simple main effects, we pass the cell totals, ANOVA table, and the fixed and across factors to our function `simple()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple main effects of Group at Trial Type\nmixedSmeGroup = simple(mixedCellTotals,mixedAnovaTable,fixed,across)\n(mixedSmeGroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       Levels Sum of Squares Degrees of Freedom Mean Square            F\n1   Congruent           80.0                  1      80.000   0.04576906\n2 Incongruent       285246.6                  1  285246.612 163.19337388\n3  Error term       136336.6                 78    1747.906   0.00000000\n             P\n1 8.311544e-01\n2 8.245446e-21\n3 0.000000e+00\n```\n:::\n:::\n\n\nAs described in the lecture, to calculate the simple main effects of a given factor in a mixed design, we use the mean square error for the main effect of that factor from the original ANOVA table as the error term. The mean square error in the simple main effects table is given in column four (Mean Square) of row three (Error term). You will notice that this is the error mean square for the main effect of Group that we calculated earlier from our initial ANOVA table (i.e., 1747.906). If you divide the between-group mean squares for the effect of Group at congruent and incongruent trials by this value, it will give you the $F$ ratios shown in the simple main effects table. \n\nLooking at the simple main effects, we can see that the simple main effect of Group at congruent trials is not significant, $p$ = 0.831. This indicates that mean response times for congruent trials did not differ between the healthy and schizophrenia groups. However, the simple main effect of Group at incongruent trials is significant, $p$ < .001. Looking at the descriptive statistics we generated earlier, we can see that this is because mean response times are longer on incongruent trials for the schizophrenia group than the healthy group. \n\nNext, we are going to calculate the simple main effects of the factor Trial Type at Group. This means, we are going to:\n\n* Test the difference between congruent and incongruent trials for the *healthy* group only.\n* Test the difference between congruent and incongruent trials for the *schizophrenia* group only.\n\nTo do this, we now need to declare Trial Type as the \"fixed\" factor and Group as the \"across\" factor: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create \"fixed\" and \"across\" factors\nfixed  = \"TrialType\"\nacross = \"Group\"\n```\n:::\n\n\nWe then generate the simple main effects of Trial Type with the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple main effects of Trial Type at Group\nmixedSmeTrialType = simple(mixedCellTotals,mixedAnovaTable,fixed,across)\n(mixedSmeTrialType)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Levels Sum of Squares Degrees of Freedom Mean Square        F\n1       Healthy       432180.0                  1  432180.000 163.6871\n2 Schizophrenia      1398411.6                  1 1398411.612 529.6451\n3    Error term       205941.9                 78    2640.281   0.0000\n             P\n1 7.609756e-21\n2 1.632592e-36\n3 0.000000e+00\n```\n:::\n:::\n\n\nRemember, to calculate the simple main effects of a given factor in a mixed design, we use the mean square error for the main effect of that factor from the original ANOVA table as the error term. The mean square error in the simple main effects table is given in column four (Mean Square) of row three (Error term). You will notice that this is the error mean square for the main effect of Trial Type that we calculated earlier from our initial ANOVA table (i.e., 2640.281). If you divide the between-group mean squares for the effect of Trial Type at healthy and schizophrenia groups by this value, it will give you the $F$ ratios shown in the simple main effects table. \n\nLooking at the simple main effects, we can see that the simple main effect of Trial Type at healthy is significant, $p$ $<$ .001. Inspecting our descriptive statistics, we can see that this is because for the healthy group, mean response times are longer for incongruent than congruent trials. The simple main effect of Trial Type at schizophrenia is also significant, $p$ $<$ .001. Looking at our descriptive statistics, we can see that this is because for the schizophrenia group, mean response times are also longer for incongruent than congruent trials. Thus, both the healthy and schizophrenia groups show a Stroop effect (longer response times for incongruent than congruent trials), but the effect is larger for the schizophrenia group, which has a much smaller $p$ value (and a correspondingly larger $F$ ratio).    \n\n### Writing up the results\n\n![Figure 1. Mean response times as a function of the group and trial type manipulations. Error bars represent 95% confidence intervals.](images/StroopMixedData.png){width=50%}\n\nFigure 1 shows mean response times as a function of the group and trial type manipulations. These data were subjected to a 2 (group: healthy *vs.* schizophrenia) $\\times$ 2 (trial type: congruent *vs.* incongruent) mixed Analysis of Variance. There was a significant main effect of group, *F*(1, 78) = 84.35, *p* $<$ .001, with longer response times in the schizophrenia group than the healthy group, a significant main effect of trial type, *F*(1, 78) = 641.11, *p* < .001, with longer response times for incongruent than congruent trials, and a significant interaction between the two factors, *F*(1, 78) = 52.22, *p* < .001. \n\nTo scrutinise the interaction, a simple main effects analysis was undertaken. For the simple main effects of group at trial type, response times on congruent trials did not differ significantly between the healthy and schizophrenia groups, *F*(1, 78) = .05, *p* = .831, whereas response times were significantly longer on incongruent trials for the schizophrenia group compared to the healthy group, *F*(1, 78) = 163.19, *p* $<$ .001. For the simple main effects of trial type at group, response times were significantly longer on incongruent trials than congruent trials for the healthy group, *F*(1, 78) = 163.69, *p* $<$ .001, and for the schizophrenia group, *F*(1, 78) = 529.65, *p* $<$ .001, although the effect was larger for the schizophrenia group.\n\nHence, the interaction arose because the schizophrenia group demonstrated a larger Stroop effect than the healthy group and this was due to longer response times on incongruent, but not congruent, trials.\n\n## Analysing hypothetical data for the fully within-participants Stroop experiment\n\nWe turn now to an analysis of the fully within-participant Stroop experiment described in the lecture. In this experiment, a researcher wants to examine whether the magnitude of the Stroop effect decreases with practice at the task. The Stroop task is administered over three successive blocks of trials and the expectation is that the magnitude of the Stroop effect will decrease gradually across blocks. She administers a multi-trial Stroop task to a single group of participants in a 2 (trial type: congruent *vs.* incongruent) $\\times$ 3 (block: block 1 *vs.* block 2 *vs.* block 3) fully within-participants design. \n\nThe data set contains seven columns:\n\n* **Participant:** represents the participant number, which ranges from 1--40, with $N$ = 40 participants. \n\n* **Congruent_Block1:** represents the mean response time, averaged across trials, for congruent trials in the first block of trials.\n\n* **Congruent_Block2:** represents the mean response time, averaged across trials, for congruent trials in the second block of trials.\n\n* **Congruent_Block3:** represents the mean response time, averaged across trials, for congruent trials in the third block of trials.\n\n* **Incongruent_Block1:** represents the mean response time, averaged across trials, for incongruent trials in the first block of trials.\n\n* **Incongruent_Block2:** represents the mean response time, averaged across trials, for incongruent trials in the second block of trials.\n\n* **Incongruent_Block3:** represents the mean response time, averaged across trials, for incongruent trials in the third block of trials.\n\n### Import data, set variables as factors, and generate descriptive statistics\n\nThere's a bit to get through in this analysis, so I am going to supply the code for everything that follows. We begin, as always, by loading our data set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import data\nstroopWithin = read_csv(\"StroopWithin.csv\")\n(stroopWithin)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 40 × 7\n   Participant Congruent_Block1 Congruent_Block2 Congr…¹ Incon…² Incon…³ Incon…⁴\n         <dbl>            <dbl>            <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1           1              627              687     563     863     742     653\n 2           2              558              681     674     870     687     647\n 3           3              635              709     575     794     728     722\n 4           4              626              673     663     872     644     686\n 5           5              610              610     643     813     729     579\n 6           6              568              655     715     856     703     745\n 7           7              635              641     573     901     695     643\n 8           8              530              677     545     818     737     672\n 9           9              613              621     638     799     699     630\n10          10              542              607     636     829     705     702\n# … with 30 more rows, and abbreviated variable names ¹​Congruent_Block3,\n#   ²​Incongruent_Block1, ³​Incongruent_Block2, ⁴​Incongruent_Block3\n```\n:::\n:::\n\n\nAs is the case for a fully within-participants design, the data are in entirely wide format and we need to get them into long format for the analysis. We are going to start by grouping the columns `Congruent_Block1` through to `Incongruent_Block3` into a new variable called `Group` using the `gather` function used previously:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert data into long format\nstroopWithinLong = stroopWithin %>%\n  gather(Group,RT,Congruent_Block1:Incongruent_Block3,factor_key = TRUE)\n(stroopWithinLong)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 240 × 3\n   Participant Group               RT\n         <dbl> <fct>            <dbl>\n 1           1 Congruent_Block1   627\n 2           2 Congruent_Block1   558\n 3           3 Congruent_Block1   635\n 4           4 Congruent_Block1   626\n 5           5 Congruent_Block1   610\n 6           6 Congruent_Block1   568\n 7           7 Congruent_Block1   635\n 8           8 Congruent_Block1   530\n 9           9 Congruent_Block1   613\n10          10 Congruent_Block1   542\n# … with 230 more rows\n```\n:::\n:::\n\n\nThe first argument to `gather()` tells R we want to create a variable called `Group`. The second argument tells R that `RT` is the dependent variable. The third argument, `Congruent_Block1:Incongruent_Block3`, tells R that we want to bundle the columns `Congruent_Block1` through to `Incongruent_Block3` into the new variable, `Group`. The fourth argument, `factor_key = TRUE`, tells R that we want to make this variable a factor. The results of this transformation have been assigned to a new data frame called `stroopWithinLong`.\n\nLooking at the new data frame we have created, we can see that it is not exactly what we want. Our new variable `Group` actually contains both of our independent variables. What we want is to separate these independent variables into two separate columns. We can do that with the `separate` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Divide Group into seperate columns for Trial Type and Block\nstroopWithinLongSep = stroopWithinLong %>%\n  separate(Group, c(\"TrialType\",\"Block\"))\n(stroopWithinLongSep)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 240 × 4\n   Participant TrialType Block     RT\n         <dbl> <chr>     <chr>  <dbl>\n 1           1 Congruent Block1   627\n 2           2 Congruent Block1   558\n 3           3 Congruent Block1   635\n 4           4 Congruent Block1   626\n 5           5 Congruent Block1   610\n 6           6 Congruent Block1   568\n 7           7 Congruent Block1   635\n 8           8 Congruent Block1   530\n 9           9 Congruent Block1   613\n10          10 Congruent Block1   542\n# … with 230 more rows\n```\n:::\n:::\n\n\nThis bit of code tells R to separate the variable `Group` into two new variables, one called `TrialType` and one called `Block`. The results are stored in a new data frame called `stroopWithinLongSep`, which is the data frame we will be using henceforth. Looking at this data frame we can see that our transformation has had the desired effect---we now have two new columns corresponding to each of our two independent variables.\n\nHowever, our two new variables are currently stored as characters (they have the labels `<chr>` beneath the variable names) and we need to convert them to factors. We also need to convert the Participant variable into a factor. So, let's do that next:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert variables into factors\nstroopWithinLongSep$Participant = factor(stroopWithinLongSep$Participant)\nstroopWithinLongSep$TrialType   = factor(stroopWithinLongSep$TrialType)\nstroopWithinLongSep$Block       = factor(stroopWithinLongSep$Block)\n```\n:::\n\n\nRight, now is as good a time as any to get some descriptive statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get descriptive statistics\nwithinDescriptives = stroopWithinLongSep %>%\n  # Organise the output by the\"TrialType\" and \"Block\" factors\n  group_by(TrialType, Block) %>%\n  # Request means, standard deviations, and confidence intervals\n  get_summary_stats(RT, show = c(\"mean\",\"sd\",\"ci\"))\n  # Print the results\n  (withinDescriptives)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n  TrialType   Block  variable     n  mean    sd    ci\n  <fct>       <fct>  <fct>    <dbl> <dbl> <dbl> <dbl>\n1 Congruent   Block1 RT          40  615.  48.9  15.6\n2 Congruent   Block2 RT          40  631.  50.8  16.3\n3 Congruent   Block3 RT          40  632.  53.8  17.2\n4 Incongruent Block1 RT          40  832.  43.7  14.0\n5 Incongruent Block2 RT          40  723.  41.2  13.2\n6 Incongruent Block3 RT          40  650.  49.1  15.7\n```\n:::\n:::\n\n\nTime is limited, so we are once again going to skip over the usual checks, which you should otherwise always perform. \n\nHowever, because one of our within-participants factors contains three levels (i.e., Block) there is one check that will be performed when we run the ANOVA. Specifically, this is a check to establish whether the **sphericity assumption** has been violated. Richard introduced you to this assumption when he discussed single-factor within-participants ANOVA, so I will only describe it briefly. The sphericity assumption states that *for a within-participants design with three or more levels, the variance of the difference scores between one pair of levels should not differ significantly from the variances of the difference scores for every other possible pair of levels.* \n\nThe assumption is tested using Mauchly's test of sphericity, which is applied to any outcome involving a factor with three or more levels. If the test result is significant, then the assumption has been violated. If this occurs, then we must adopt the Greenhouse-Geisser correction for violations of this assumption.\n\n### Running the mixed ANOVA\n\nTo run our ANOVA, we are once again going to use the `anova_test` function from the `rstatix` package. The code required to run the ANOVA is given below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the within-participants design ANOVA model\nstroopWithinModel = anova_test(data = stroopWithinLongSep, dv = RT, wid = Participant, within = c(TrialType, Block), detailed = TRUE)\n(stroopWithinModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nANOVA Table (type III tests)\n\n$ANOVA\n           Effect DFn DFd         SSn      SSd         F        p p<.05   ges\n1     (Intercept)   1  39 111105237.6  77509.9 55903.885 3.54e-63     * 0.995\n2       TrialType   1  39    713623.2  84476.3   329.457 1.28e-20     * 0.568\n3           Block   2  78    272694.5 221792.5    47.951 2.63e-14     * 0.335\n4 TrialType:Block   2  78    403873.6 158005.4    99.687 3.25e-22     * 0.427\n\n$`Mauchly's Test for Sphericity`\n           Effect     W     p p<.05\n1           Block 0.949 0.368      \n2 TrialType:Block 0.952 0.394      \n\n$`Sphericity Corrections`\n           Effect   GGe      DF[GG]    p[GG] p[GG]<.05   HFe   DF[HF]    p[HF]\n1           Block 0.951   1.9, 74.2 1.01e-13         * 0.999  2, 77.9 2.72e-14\n2 TrialType:Block 0.954 1.91, 74.44 2.61e-21         * 1.002 2, 78.17 3.25e-22\n  p[HF]<.05\n1         *\n2         *\n```\n:::\n:::\n\n\nTo create the model, the first argument we supplied to `anova_test` was the name of our data, `stroopWithinLongSep`. The second argument we supplied was our dependent variable, `RT`. The third argument we supplied was `Participant`, which is the column containing the individuals/participants identifier. The fourth argument we supplied was our two within-participants factors, `TrialType` and `Block`. \n\nThe ANOVA output now contains three tables. The first is the main ANOVA table, which is organised in the same format as that produced for our mixed design example from earlier. \n\nThe second table presents the results of Mauchly's test of sphericity, which has been applied to the factor Block, which has three levels, and the interaction between Trial Type and Block. In both instances, we can see that the test result is non-significant, which means the sphericity assumption has been met.\n\nThe third table gives the Greenhouse-Geisser corrected ANOVA table for the main effect of Block and the interaction between Trial Type and Block. Had we violated the sphericity assumption, it is these values that we would report when writing up our ANOVA, instead of the values taken from the original ANOVA table (the main effect of Trial Type would be drawn from the original ANOVA table as it only has two levels, and therefore the sphericity assumption does not apply to this outcome). Because we did not violate the sphericity assumption on this occasion, we can focus solely on the original ANOVA table. \n\nYou may at this point be wondering why Mauchly's test of sphericity and the Greenhouse-Geisser correction were not produced when we ran the ANOVA for our mixed design example. The answer is simple; for that design our within-participants factor only contained two levels, so the sphericity assumption did not apply. The `anova_test` function only generates these tests and corrections when at least one of the within-participants factors has three or more levels.\n\nLet's redirect our attention to the original ANOVA table. We can see that there is a significant main effect Trial Type, *p* $<$ .001. Looking at our descriptive statistics, we can see that this arose because response times are longer for incongruent than congruent trials. There is also a significant main effect of Block, *p* $<$ .001, which arose because response times get quicker across blocks as participants obtain more experience with the task. There is also a significant interaction between the two factors, *p* $<$ .001. We will defer interpretation of this interaction until later, once we have calculated the simple main effects and plotted the data. \n\nAs for our mixed design example, the ANOVA table does not include the mean square values for the outcomes. Previously, we calculated the between-group and error mean squares for ourselves, and verified that these produced the obtained $F$ ratios when we divided the former by the latter. This time, we will just generate the error mean squares. Again, this is so I can show you which error term is being used to test each ANOVA outcome and the simple main effects of each factor. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the error mean sum of squares\nwithinMeanSquareError = stroopWithinModel$ANOVA$SSd/stroopWithinModel$ANOVA$DFd\n# Exclude the intercept (row 1 of 4) from the results\nwithinMeanSquareError[2:4]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2166.059 2843.493 2025.710\n```\n:::\n:::\n\n\nThe first value is the error mean square for the main effect of Trial Type (2166.059), the second value is the error mean square for the main effect of Block (2843.493), and the third value is the error mean square for the interaction (2025.710). Recall that in the lecture, we saw that in a fully within-participants design the two main effects and the interaction each have their own error terms, and sure enough we can see that the error term is different for each outcome.\n\n### Simple main effects\n\nSince our interaction is once again significant, we need to proceed to calculate the simple main effects. Before we can calculate the simple main effects, there are a few things we need to do. First, we need to store our ANOVA table in a dataframe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get ANOVA table\nwithinAnovaTable = get_anova_table(stroopWithinModel)\n```\n:::\n\n\nNext, we need to calculate the cell totals for each of the six conditions and the number of observations (i.e., scores) in each cell:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate cell totals and counts\nwithinCellTotals = stroopWithinLongSep %>%\n  # Organise the output by the TrialType\" and \"Block\" factors\n  group_by(TrialType, Block) %>%\n  # Request cell totals and number of observations (i.e., scores)\n  summarise(sum = sum(RT),n = n())\n  # Print the results\n  (mixedCellTotals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 4\n# Groups:   TrialType [2]\n  TrialType   Group           sum     n\n  <fct>       <fct>         <dbl> <int>\n1 Congruent   Healthy       24919    40\n2 Congruent   Schizophrenia 24999    40\n3 Incongruent Healthy       30799    40\n4 Incongruent Schizophrenia 35576    40\n```\n:::\n:::\n\n\nThen, we need to specify which simple main effects we want to generate. We are first going to calculate the simple main effects of the factor Trial Type at Block. This means, we are going to:\n\n* Test the difference between congruent and incongruent trials for *Block 1* only.\n* Test the difference between congruent and incongruent trials for *Block 2* only.\n* Test the difference between congruent and incongruent trials for *Block 3* only.\n\nNotice that because Trial Type has only two levels, the simple main effects of this factor involve only pairwise comparisons. To generate these simple main effects, we need to declare Trial Type as the \"fixed\" factor (we are always comparing the congruent and incongruent trials) and Block as the \"across\" factor (the comparison between the congruent and incongruent trials occurs \"across\" the Block 1, Block 2, and Block 3 levels of the Block factor): \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create \"fixed\" and \"across\" factors\nfixed  = \"TrialType\"\nacross = \"Block\"\n```\n:::\n\n\nTo get the simple main effects of Trial Type, we pass the cell totals, ANOVA table, and the fixed and across factors to our function `simple()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple main effects of Trial Type at Block\nwithinSmeTrialType = simple(withinCellTotals,withinAnovaTable,fixed,across)\n(withinSmeTrialType)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Levels Sum of Squares Degrees of Freedom Mean Square          F\n1     Block1     941997.012                  1  941997.012 434.889848\n2     Block2     168820.312                  1  168820.312  77.938931\n3     Block3       6679.512                  1    6679.512   3.083717\n4 Error term      84476.296                 39    2166.059   0.000000\n             P\n1 9.362214e-23\n2 7.711308e-11\n3 8.693084e-02\n4 0.000000e+00\n```\n:::\n:::\n\n\nAs described in the lecture, to calculate the simple main effects of a given factor in a within-participants design, we use the mean square error for the main effect of that factor from the original ANOVA table as the error term. The mean square error in the simple main effects table is given in column four (Mean Square) of row three (Error term). You will notice that this is the error mean square for the main effect of Trial Type that we calculated earlier from our initial ANOVA table (i.e., 2166.059). If you divide the between-group mean squares for the effect of Trial Type at Block 1, Block 2, and Block 3 by this value, it will give you the $F$ ratios given in the simple main effects table. \n\nLooking at the simple main effects, we can see that the simple main effect of Trial type at Block 1 is significant, $p$ $<$ .001. Looking at our table of descriptive statistics, we can see that this is because mean response times for incongruent trials were longer than for congruent trials. The simple main effect of Trial Type is also significant at Block 2, $p$ $<$ .001, again reflecting longer mean response times for incongruent than congruent trials. However, the simple main effect of Trial Type at Block 3 is not significant, $p$ = .087. Thus, we obtained a statistically reliable Stroop effect for Blocks 1 and 2, but not for Block 3.    \n\nNext, we are going to calculate the simple main effects of the factor Block at Trial Type. This means, we are going to:\n\n* Test the differences between Block 1, Block 2, and Block 3 for *congruent* trials only.\n* Test the differences between Block 1, Block 2, and Block 3 for *incongruent* trials only.\n\nNotice that because Block has three levels, the simple main effects of this factor involve more than simple pairwise comparisons. To test these simple main effects, we now need to declare Block as the \"fixed\" factor and Trial Type as the \"across\" factor: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create \"fixed\" and \"across\" factors\nfixed  = \"Block\"\nacross = \"TrialType\"\n```\n:::\n\n\nWe then generate the simple main effects of Block with the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple main effects of Block at Trial Type\nwithinSmeBlock = simple(withinCellTotals,withinAnovaTable,fixed,across)\n(withinSmeBlock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       Levels Sum of Squares Degrees of Freedom Mean Square          F\n1   Congruent       7616.717                  2    3808.358   1.339324\n2 Incongruent     668951.450                  2  334475.725 117.628461\n3  Error term     221792.467                 78    2843.493   0.000000\n             P\n1 2.679808e-01\n2 2.828545e-24\n3 0.000000e+00\n```\n:::\n:::\n\n\nRemember, to calculate the simple main effects of a given factor in a within-participants design, we use the mean square error for the main effect of that factor from the original ANOVA table as the error term. The mean square error in the simple main effects table is given in column four (Mean Square) of row three (Error term). You will notice that this is the error mean square for the main effect of Block that we calculated earlier from our initial ANOVA table (i.e., 2843.493). If you divide the between-group mean squares for the effect of Block at congruent and incongruent trials by this value, it will give you the $F$ ratios given in the simple main effects table. \n\nLooking at the simple main effects, we can see that the simple main effect of Block at congruent trials is not significant, $p$ = .268. Hence, mean response times do not differ reliably across blocks for congruent trials. However, the simple main effect of Block at incongruent trials is significant, $p$ $<$ .001. Since there are three levels in the factor Block, this significant simple main effect is like the outcome of a significant single-factor ANOVA with three levels---it tells us that there are differences between the group means, but it does not tell us where they are located. To find out, we need to perform some follow up tests. We have a few options available to us. \n\nSuppose we hypothesised the interaction from the beginning and that we are only interested in the difference between Block 1 and Block 2, and Block 2 and Block 3 for incongruent trials, but we are not interested in the third comparison, which is between Block 1 and Block 3. In this case, we would have specified planned comparisons, because we do not intend to conduct all possible comparisons, only the ones relevant to testing our specific hypotheses. In this case, we could simply run two repeated measures $t$-tests, one comparing Block 1 and Block 2 at incongruent trials, and one comparing Block 2 and Block 3 at incongruent trials. Should we apply the Bonferroni correction to these comparisons? One rule of thumb is that if the number of comparisons is one less than the number of levels, i.e., ($a$-1) comparisons where $a$ is the number of levels in the factor, then we do not need to apply the Bonferroni correction. In our case, our simple main effect has three levels and we are conducting two comparisons, which is one less than the number of levels, so we can proceed without using the Bonferroni correction (for those occasions where there are four or more levels, this rule of thumb does not apply and you should definitely use the Bonferroni correction). Alternatively, suppose we did not specify at the outset which comparisons we would perform if the interaction was significant. In this case, we would perform all three comparisons and we would use a post-hoc test, such as the Tukey test. \n\nFour our purposes, we are going to perform planned comparisons. To perform these comparisons, we first need to filter our data so that they only contain responses on incongruent trials (we are excluding responses on congruent trials). The following code gives us what we want:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter the data so they only contain responses on \"Incongruent\" trials\nfilter4SME = filter(stroopWithinLongSep, TrialType == \"Incongruent\")\n(filter4SME)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 120 × 4\n   Participant TrialType   Block     RT\n   <fct>       <fct>       <fct>  <dbl>\n 1 1           Incongruent Block1   863\n 2 2           Incongruent Block1   870\n 3 3           Incongruent Block1   794\n 4 4           Incongruent Block1   872\n 5 5           Incongruent Block1   813\n 6 6           Incongruent Block1   856\n 7 7           Incongruent Block1   901\n 8 8           Incongruent Block1   818\n 9 9           Incongruent Block1   799\n10 10          Incongruent Block1   829\n# … with 110 more rows\n```\n:::\n:::\n\n\nThe new data frame `filter4SME` is a version of our data in which only congruent trials are included. We can then use the `pariwise_t_test` function that you have used many times to run our $t$-tests (making sure to specify `paired = TRUE` as we want repeated measures comparisons!):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter4SME %>% \n  # Generate the t-tests for the two comparisons of interest\n  pairwise_t_test(RT ~ Block, paired = TRUE,\n    # Specify the comparisons we want\n    comparisons = list(c(\"Block1\",\"Block2\"),c(\"Block2\",\"Block3\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 10\n  .y.   group1 group2    n1    n2 statistic    df        p    p.adj p.adj.signif\n* <chr> <chr>  <chr>  <int> <int>     <dbl> <dbl>    <dbl>    <dbl> <chr>       \n1 RT    Block1 Block2    40    40      9.90    39 3.38e-12 6.76e-12 ****        \n2 RT    Block2 Block3    40    40      7.03    39 1.96e- 8 1.96e- 8 ****        \n```\n:::\n:::\n\n\nThe comparison between Block 1 and Block 2 is significant, *p* $<$ .001, as is the comparison between Block 2 and Block 3, *p* $<$ .001. Looking at our descriptive statistics, we can see that this is because mean response times are faster for incongruent trials in Block 2 than in Block 1, and mean response times for incongruent trials are faster in turn in Block 3 than in Block 2. Thus, with practice on the Stroop task, participants responses on incongruent trials get gradually quicker.\n\n### Writing up the results\n\n![Figure 2. Mean response times as a function of the trial type and block manipulations. Error bars represent 95% confidence intervals.](images/StroopWithinData.png){width=50%}\n\nFigure 2 shows mean response times as a function of the trial type and block manipulations. These data were subjected to a 2 (trial type: congruent *vs.* incongruent) $\\times$ 3 (block: block 1 *vs.* block 2 *vs* block 3) fully within-participants Analysis of Variance. There was a significant main effect of trial type, *F*(1, 39) = 329.46, *p* < .001, with response times being longer for incongruent than congruent trials, a significant main effect of block, *F*(2, 78) = 47.95, *p* < .001, with response times getting quicker across blocks, and a significant interaction between the two factors, *F*(2, 78) = 99.69, *p* < .001. \n\nTo scrutinise the interaction, a simple main effects analysis was undertaken. For the simple main effects of trial type at block, response times were significantly longer on incongruent trials than congruent trials in block 1, *F*(1, 39) = 434.89, *p* < .001, and block 2, *F*(1, 39) = 77.94, *p* < .001, but not in block 3, *F*(1, 39) = 3.08, *p* = .087. Turning to the simple main effects of block at trial type, response times did not differ significantly across blocks for congruent trials, *F*(2, 78) = 1.34, *p* = .268, but they did differ significantly across blocks for incongruent trials, *F*(2, 78) = 117.63, *p* < .001. Planned comparisons revealed that response times on incongruent trials were faster in block 2 than in block 1, *t*(39) = 9.90, *p* < .001, and faster in turn in block 3 than in block 2, *t*(39) = 7.03, *p* < .001. \n\nHence, the interaction arose because the magnitude of the Stroop effect decreased across blocks and this was due to the speeding up of responses on incongruent, but not congruent, trials.\n\n### Additional tasks\nPhew!!! We have covered a lot of ground in today's session -- well done for making it through the exercises. If you should happen to want more, then you could recreate the plots in Figures 1 and 2 by co-opting the code we used to generate line plots in lab session 6. \n\n<br>\n<br>\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}