{
  "hash": "08496041e715825e876a983bebdb4036",
  "result": {
    "markdown": "---\ntitle: 3. Multiple regression models that include interactions (moderated variables)\nsubtitle: Emma Mills\norder: 4\n---\n\n\n\n\n\n# Lecture\n\nAccess the lecture [here](https://modules.lancaster.ac.uk/mod/url/view.php?id=2045473)\n\nThe lecture materials, including and and R files are downloaded from [here](data/Wk3/Lecture 3 Materials.zip) as a zip file. You can upload the zip file directly on to the R server and it will populate a new folder with the files and data files automatically.\n\n\n## Interactions\n\n+ When one variable moderates the effect of another variable on the outcome variable, Or\n  + When a coefficient for one predictor changes its size when it moves between the levels or values of another predictor, Or\n  + The change that one predictor predicts for the outcome variable depends on a specific level of another predictor\n+ Moderation – a process for exploring the differing conditions under which two or more variables may work together.  \n\nIn a simple regression, such as below, we test the effect of a single predictor on our dependent variable. In this case, the IQ of a mother on a child's test score.\n\n![Simply regression](Images/Wk3/Regression.png)\n\nIf we were to add in another variable that groups the data somehow, perhaps mother's high school completion (Yes or No), then we may see that there are two lines that represent the two groups in a plot:\n\n![Regression with no interaction](Images/Wk3/RegressionGroup.png)\nIn the example above, there is no interaction, regardless of group, child test scores increase as a constant rate from an effect of Mother's IQ. One may be slightly higher, indicating one group typically shows a greater IQ, but this increases at a constant rate.\n\nIn the example below, the lines cross, which means that we have an interaction. Something in the two predictors, IQ and high school completion means that they interact with each other, and have an influence on each other as well as the dependent variable. \n\n![Regression with amn interaction](Images/Wk3/RegressionInteract.png)\n### What are interaction terms?\n\nModel for multiple regression with two independent predictors:\n$Y=𝑏_0+ 𝑏_1𝑋_1 + 𝑏_2𝑋_2 + 𝑒$\n\n+ We interpret each predictor as representing a value of the variable’s influence on the outcome variable while holding all other predictors constant\n\nIn the diagram of the multiple regression model below, note that $X_1$ and $X_2$ do not talk to each other – only Y\n\n\n\n\n\n\nSometimes, we need to consider one variable’s influence on the outcome variable at different levels of another predictor:  we need interactions.\nThese are expressed like this in the equation:\n$Y=𝑏_0 + 𝑏_1X_1 + 𝑏_2X_2 + b_3\\times(X_1𝑋_2)+ 𝑒$\n\nSee how in the diagram below, $X_1$ and $X_2$ *do*  talk to each other – and they both talk to Y as well\n\n\n\n\n\nInteractions are the product term of two (or more) predictors\n+ We multiply two (or more) variables together\n+ You can do this outside the model and create a new variable in your dataset\n+ Or you can write it into your model formula\n\nIntroducing an interaction term means that the predictors within the term are no longer acting independently of each other\n+ Interaction terms tend to strengthen or weaken the coefficients’ independent effects\n\nNow, a predictor’s effect is conditional upon the level of another predictor (example coming)\n\n\n## When are interaction terms used?\n\nTheory may predict them, and so research questions/hypotheses may predict them.\n\nStudy design may implicitly suggest them (groups?)\n\nResults may suggest them\n+ Regression coefficients that seem large when modelled independently may suggest the need for an interaction term\n+ Make sure you are aware of where you are in the analysis workflow\n+ Don’t just add them\n+ Save any unplanned additions of interaction terms for  an exploratory analysis phase...\n\n## Statistical Power of Interactions\n\nMany effect sizes in psychology hover around Cohen’s *d* = 0.4\n\nBased upon an effect size like this:\n+ The power of an interaction can be a small as 1/16th of the independent effects within a model (Gelman et al. 2020) \n+ This is for ANOVA and regression methods\n+ This is when all the assumptions of the model are met\n+ Most models violate model assumptions in some way\n+ Although relatively tolerant of violations:\n+ Power of the effects are thus reduced further...\n\n## Preparation of data for using interactions\n\nCentre or standardise your continuous variables as standardising puts both predictors on the same scale. So interpreting the effect of one predictor on the other will be using the same scale of units\n\nConsider how to use your categorical variables\n+ Dummy coding..?\n+ Sum coding..?\n+ Making new binary variables…?\n+ Coercing a binary variable to numeric class and mean centring\n+ (so many choices! So little time!)\n\n## Building a model with interactions\n\nPlan to build the model suggested by your research questions/hypotheses/theory. If that includes the interaction term, build it as the first model. If not, \n+ Build an independent predictor model first\n+ Build a further model that includes independent and interaction terms\n\nQuestion:  does a study design that uses different groups of people, implicitly motivate an interaction term?\n\nThis implies more than one model; multiple regression equals multiple models\n\nA cautious and conservative approach to multiple regression is to create several models, each one building upon the next\n+ These are called “nested” models\n+ Every model uses exactly the same data\n+ The latest model has all of the previous models within it\n+ The latest model can differ by +1 predictor or more\n\n![Nested models](Images/Wk3/Nested.png)\n\n## What model to report?\n\nYou can inspect the $R^2$ or adj. $R^2$ values to see if the more complex model explains more variance in the outcome variable.\nBut more principled is to use an inferential test:\n+ Use `anova()` to formally test the null hypothesis that two models explain the same amount of variance in the outcome variable = model comparison\n+ If so, p-value is > .05, \n+ we fail to reject the null hypothesis\n+ AND we choose the simpler model\n+ If the p-value of the anova < .05\n+ we reject the null hypothesis \n+ we choose the more complex model\n\n![Comparison of models](Images/Wk3/aov.png)\n### Hazard Warning!\n\nThis is where *p*-hacking, cherry picking and HARKing can occur really easily. Strategies to defend against such questionable research practices: (remember from PSYC123 last year)\n+ State clearly whether you are in confirmatory or exploratory analysis mode\n+ Explain your process to yourself and your future reader before you start (at best in a pre-registration; at the very least before you begin)\n+ Report all models – use a script such as .Rmd file or an interactive notebook so that the process is recorded and can be reproduced\n+ Be honest and comprehensive in your reporting.\n\n\n## Import Packages and Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(include = TRUE)\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   1.0.1 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.3.0      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(effects)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(gridExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'gridExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    combine\n```\n:::\n\n```{.r .cell-code}\nlibrary(PerformanceAnalytics)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: xts\nLoading required package: zoo\n\nAttaching package: 'zoo'\n\nThe following objects are masked from 'package:base':\n\n    as.Date, as.Date.numeric\n\n\nAttaching package: 'xts'\n\nThe following objects are masked from 'package:dplyr':\n\n    first, last\n\n\nAttaching package: 'PerformanceAnalytics'\n\nThe following object is masked from 'package:graphics':\n\n    legend\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- read_csv(\"KidIQ.txt\", col_types = cols(mom_work = col_skip()))\n```\n:::\n\n::: {.cell}\n\n:::\n\nNotice how I have turned the `knitr::opts_chunk$set(include = TRUE)` line of code above to TRUE, this is what prints the code and output when you knit the document.  Switching TRUE to FALSE will stop the code from printing out when you knit - try it.  You can't break anything!\n\nLast week, we worked with multiple regression models that contained both continuous and categorical predictors.  This week we continue to work with a mix of predictor variables and introduce the next step - interaction terms.\n\nWhen an interaction term is entered into a model and is found to be significant (*p* < .05), this means that the rate of change in the outcome variable changes as the levels in the predictor variables change.  We have to consider the independent effects of the predictors that are in the interaction term and infer whether the interaction effect is a weakening or a strengthening of the outcome variable.  Here is a plot to illustrate what I mean:\n\n## Visualise\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(d, aes(mom_iq, kid_score)) +\n  geom_point() +\n  geom_abline(\n  intercept = c(-10),\n  slope = c(1),\n  color = c(\"black\")) +\n  scale_color_manual(values = c(\"black\")) +\n  labs(x = \"Mother IQ Score\", y = \"Child Test Score\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# code to show parallel lines as illustration of no interaction.\n# ggplot(d, aes(mom_iq, kid_score)) +\n#   geom_point(aes(color = factor(mom_hs)), show.legend = FALSE) +\n#   geom_abline(\n#   intercept = c(-20.59, 11), # different starting places.\n#   slope = c(1, 1),  # both slopes rise at the same rate - no differences \n#   color = c(\"black\", \"grey\")) +\n#   scale_color_manual(values = c(\"black\", \"grey\")) +\n#   labs(x = \"Mother IQ Score\", y = \"Child Test Score\") + \n#   theme_bw()\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nThis plot shows a distribution of 3 year old child test scores (y- axis - outcome variable) and how they correlate with their mother's IQ Score (x-axis, predictor variable).  They grey and the black colours of the dots further denote a grouping variable - whether the mother of the child finished high school or not (yes or no).\n\nFor the purposes of illustrating the interaction, it is not important to know which colour represents which group.  Suffice it to say that the plot shows an interaction between high school graduation status and mother's IQ score.  We know this because the black and grey regression lines are not parallel across the plot.  The rate of change for Mother's IQ on child test scores is not the same for both levels of mother's high school graduation status.\n\nAbove, I talked about an interaction effect either weakening or strengthening a relationship with the outcome variable.  Both are present here and it depends which group you want to focus on to decided whether the relationship is weaker or stronger.\n\nLook at the black line on the plot - at the left hand side, it begins at a lower starting score than the grey line.  As you move across the values of mother's IQ, however (move to the right in the plot, tracing the black line), and as mother's IQ gets higher,  the black line crosses the grey line, and those children whose mother is in the black group for high school completion status and whose mother has higher IQ, end up scoring higher test scores than the child who mother is in the grey group for high school completion status and also has the same level of IQ.  This is a strengthening relationship.\n\nLet's draw the plot again to reduce the need to scroll up and down the page:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nNow focus on the grey line.  This is the other group for mother's high school completion status.  At lower IQ levels, the children in this group begin with higher test scores than the other children whose mothers are in the black group,  however, by the time we get to the higher levels of mother's IQ at the right hand side of the plot, the children of this group have lower test scores.  The rate of change in test scores for children in the grey group is slower across the values of Mother's IQ.  It is a weakened relationship of the influence of Mother's IQ on the child's test scores within this group.\n\nYou can also see the relationship in the slant of the slopes:\n\nIrrespective of whether the coefficient shows a positive or a negative relationship:\n\nA slower rate of change, or a weakening relationship will have a flatter or a more shallow slope.\n\nA faster rate of change, or a strengthening relationship will have a steeper slope.\n\nIn this demonstration, we will model an interaction term, and interpret it. First we will build models that contain only the independent predictors. Then we will add onto the model the interaction term.   We will use a model comparison routine to look support decision making as to which model is a better fit for the data.\n\n\n## The Multilple Regression Equation\n\n### Multiple Regression With Only Independent Predictors\n\nKeep the model for multiple regression in mind:\n\nYou have seen the two predictor regression model equation before:\n\n$$\nY_i = b_0 + b_1 * X_1 + b_2*X_2 + e_i\n$$\n\n### Multiple Regression With Independent Predictors & Interaction Term\nA small extension includes the product of $X_1$ and $X_2$ multiplied by a further beta coefficient\n\n$$\nY_i = b_0 + b_1 * X_1 + b_2*X_2 + b_3*(X_1*X_2) +e_i\n$$\n  -  $X_1$ and $X_2$ can be categorical predictors, continuous predictors or a mix of each.\n\n## Visualise The Data\n\nThe data set is retrieved from https://github.com/avehtari/ROS-Examples/tree/master/KidIQ/\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  kid_score mom_hs mom_iq mom_age\n      <dbl>  <dbl>  <dbl>   <dbl>\n1        65      1  121.       27\n2        98      1   89.4      25\n3        85      1  115.       27\n4        83      1   99.4      25\n5       115      1   92.7      27\n6        98      0  108.       18\n```\n:::\n:::\n\n - kid_score = test score @ 3 yrs of age = outcome variable\n - mom_hs = a categorical variable. At the moment, R is seeing it as numerical so we can use it as an indicator variable. 1 = kid's mom completed high school, 0 = kid's mom did not complete high school.\n - mom_iq = the IQ score of the kid's mom\n - mom_age = mother's age at the time of birth\n \n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d) # look at means and ranges within each variable\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   kid_score         mom_hs           mom_iq          mom_age     \n Min.   : 20.0   Min.   :0.0000   Min.   : 71.04   Min.   :17.00  \n 1st Qu.: 74.0   1st Qu.:1.0000   1st Qu.: 88.66   1st Qu.:21.00  \n Median : 90.0   Median :1.0000   Median : 97.92   Median :23.00  \n Mean   : 86.8   Mean   :0.7857   Mean   :100.00   Mean   :22.79  \n 3rd Qu.:102.0   3rd Qu.:1.0000   3rd Qu.:110.27   3rd Qu.:25.00  \n Max.   :144.0   Max.   :1.0000   Max.   :138.89   Max.   :29.00  \n```\n:::\n:::\n\n\nRight now, the R environment sees all the variables as numeric, (blue button also). Lets visualise the variables now and have a look at the relationships between them:  \n\nWhen using this code,  the c(2:4) part is calling the numeric columns of the dataset. Notice that I don't include kid_score in this group.  That's because I am going to use this as the outcome variable.\n\n### Graphical Visualisation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(2:4)], histogram=TRUE, pch=19)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nEven though R sees all the variables as numeric, you can clearly see the binary structure of the `mom_hs` variable with two levels at 0 and 1, and that the values are not evenly split within the variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(d$mom_hs) # how many values are in each level of mom_hs?\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1 \n 93 341 \n```\n:::\n:::\n\n\n## Model\n\nProgress in school is often talked about as better for children whose parents value school. We could use the variable `mom_hs` as a proxy measure for this. We can see from the `table()` function above that there are almost 4 times as many parents who completed high school than didn't in the dataset - an unbalanced variable.    But before we do that, lets begin to build some models.  Lets construct an intercept only or an empty model and see what the average 3 year old test score for this sample is:\n\nAn intercept only model is basically a model for the average test score:  you can test this by calculating the mean before you model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(d$kid_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 86.79724\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m0 <- lm(kid_score ~ 1, d)) # putting just 1 = estimate the intercept.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ 1, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-66.797 -12.797   3.203  15.203  57.203 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  86.7972     0.9797   88.59   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.41 on 433 degrees of freedom\n```\n:::\n:::\n\nWith no other predictors, the average test score is 86.  We can reject the null hypothesis that the kids score is zero (one sample t(433) = 88.59, *p* < .001)\n\nLets build another model: Above we discussed how a parent's value or belief in education is theorised to predict their offspring's progress.  We have operationalised this theory by having the `mom_hs` variable predict the `kid_score` outcome variable:  completing high school represents behaviour that shows a belief in education.\n\nBefore we do - think about how R sees this binary variable - two levels - 0 and 1, with the lowest numerical value being estimated in the intercept.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1 <- lm(kid_score ~ mom_hs, d)) # by default, lm() will model the \"1\" so it does not needed to be hard coded when other predictors are present\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ mom_hs, data = d)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-57.55 -13.32   2.68  14.68  58.45 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   77.548      2.059  37.670  < 2e-16 ***\nmom_hs        11.771      2.322   5.069 5.96e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.85 on 432 degrees of freedom\nMultiple R-squared:  0.05613,\tAdjusted R-squared:  0.05394 \nF-statistic: 25.69 on 1 and 432 DF,  p-value: 5.957e-07\n```\n:::\n:::\n\nRemember that the mother's who did not complete high school are represented in the intercept term, so the coefficient for `mom_hs` represents the difference in test scores between 3 year olds whose mothers did not and who did complete high school - a difference of approximately 12 points.\n\n## Transform\n\nBut the variable was unbalanced, remember. Ninety-three moms had not completed high school compared to 341 who had, and it was recommended by Gelman and colleagues (2020) to code those variables as 0 and 1 and then take away the mean - effectively centring your binary categorical variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$c_mom_hs <- d$mom_hs - mean(d$mom_hs) # mean centring mom_hs\n\nhead(d$c_mom_hs) # positive values = mom completed high school\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  0.2142857  0.2142857  0.2142857  0.2142857  0.2142857 -0.7857143\n```\n:::\n:::\n\n\n## Model\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1_c <- lm(kid_score ~ c_mom_hs, d)) # by default, lm() will model the \"1\" so it does not needed to be hard coded when other predictors are present\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ c_mom_hs, data = d)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-57.55 -13.32   2.68  14.68  58.45 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   86.797      0.953  91.082  < 2e-16 ***\nc_mom_hs      11.771      2.322   5.069 5.96e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.85 on 432 degrees of freedom\nMultiple R-squared:  0.05613,\tAdjusted R-squared:  0.05394 \nF-statistic: 25.69 on 1 and 432 DF,  p-value: 5.957e-07\n```\n:::\n:::\n\n\nNow the intercept is for test scores with mom's high school completion at their mid value: the average value of `kid_score` has returned, because the intercept reflects the average when the predictors are at 0 - the grand mean.\n\nLets do the math: predicted kid score = intercept + ($b_1$ * mom_hs status):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n86.797 + (11.771 * 0.2142857) # predicted score for child who mom completed hs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 89.31936\n```\n:::\n\n```{.r .cell-code}\n86.797 + (11.771 * -0.7857143) # predicted score for child whose mom did not complete hs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.54836\n```\n:::\n:::\n\n\nThe predicted score for children whose mom didn't complete high school in model 1_c is the same as the predicted score in model 1 where the intercept reflects that group.\n\n## Communicate\n\nIf this was the only model we constructed, we could interpret the model like this:\n\nOur model of mother's high school predicting test scores is significant (F(1, 432) = 25.69, *p* < .001). The proportion of variance on test scores explained by the model is approximately 6%.  Mother's educational status significantly predicts kids' test scores (t = 5.07, *p* < .001). We can reject the null hypothesis that the status of mom's high school education has no effect on kids_score.  The difference between a child's test score when mom did not complete high school and a child's test score when mom did complete high school is 11.77 points.\n\nWhen you get a model output, try interpreting it and writing it out.  You can use the above as a template / model upon which to base your early attempts.  If you are unsure about what happens, compute the maths.\n\n### Comparing models\n\nBut when we make a series of models, we don't interpret every model fully each time. Before we interpret a model, we need to make a decision about which is the better model.  \n\nTwo ways of thinking about making a series of regression models:\n\n1: A principled method is to construct the model that is indicated by the research questions and report that model.  This may be in the context of a confirmatory analysis or be regarded as a theory guided approach.  \n\n2: When a line of research is very new, data may be collected in an exploratory research framework.  The data may be analysed to reveal patterns that then lead to research questions and confirmatory research designs.  Model comparison is a method that can guide model choice. Essentially, it will help you decide if a more complex model (a model with more predictors or independent & interaction terms) is warranted.  \n\n`m0` above is an intercept model.  `m1` and `m1_c` are equivalent models - it's just that the predictor has been transformed in `m1_c`. These are models with the intercept term plus one predictor.  `m1` is the more complex model of the two.\n\nIt is much better to choose a simpler model when two models differ only on the number of predictors but pretty much explain the same amount of variance in the outcome variable.\n\nThe difference between `m0` and the others seems to be about 5% of the explained variance (m1 $R^2$ = 5%), so they seem to be doing a better job of predicting test scores.  But we can check this using an inferential test.\n\nWe can check how models compare to each other using the `anova()` function:  I will demonstrate first rather than explain so that we have something concrete to refer to:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m0, m1) # test for a difference between the models\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ 1\nModel 2: kid_score ~ mom_hs\n  Res.Df    RSS Df Sum of Sq     F    Pr(>F)    \n1    433 180386                                 \n2    432 170261  1     10125 25.69 5.957e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe output shows an analysis of variance table - you have seen these before. Our two models are model 0 and model 1 in the raw variables,  look at the formula lines of `Model 1` and `Model 2`, and the `anova` function has used each of the models as if they are factors, like in an ANOVA study.\n\nThe degrees of freedom are from the models, as are the residual sums of squares (RSS):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetrics_m0 <- augment(m0)\nmetrics_m0$RSS <- metrics_m0$.resid*metrics_m0$.resid\nsum(metrics_m0$RSS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 180386.2\n```\n:::\n\n```{.r .cell-code}\nmetrics_m1 <- augment(m1)\nmetrics_m1$RSS <- metrics_m1$.resid*metrics_m1$.resid\nsum(metrics_m1$RSS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 170261.2\n```\n:::\n:::\n\n\nAnd the *F* ratio tests calculates the difference between these two values, to see if the difference in the variance explained is significantly different from zero.\n\nI said to you that the models `m1` and `m1_c` were equivalent. Lets check the ANOVA table for the model `m1_c` in comparison with `m1`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1, m1_c) # test for a difference between the models\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ mom_hs\nModel 2: kid_score ~ c_mom_hs\n  Res.Df    RSS Df  Sum of Sq F Pr(>F)\n1    432 170261                       \n2    432 170261  0 2.9104e-11         \n```\n:::\n:::\n\nThere is no difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m0, m1_c) # test for a difference between the models\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ 1\nModel 2: kid_score ~ c_mom_hs\n  Res.Df    RSS Df Sum of Sq     F    Pr(>F)    \n1    433 180386                                 \n2    432 170261  1     10125 25.69 5.957e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\nAnd the comparison between `m0` and `m1_c` gives exactly the same output as the ANOVA for `m0` and `m1`.\n\nTo interpret these kinds of model comparison tests:\n\nModel 1 is the first model in the list that we give to the ANOVA function, Model 2 is the second, and so on. We need to check that one of the models differs from the other model in complexity by checking the `Df` column.  Here, it reads as 1 so model two is more complex by one predictor. And then we see that the *p* value is < .001. The variance explained by adding the additional predictor is significantly different from the variance explained by the smaller model.  The significant difference, justifies the added complexity, so the more complex model is preferred.\n\nAnd then we choose whether we build another model. Can you see how the visualise - transform - model cycle iterates again and again in the analysis workflow?\n\nNext we'll add `mom_age` at birth of the child.  I am choosing to do this, reasoning that the it may be more likely for younger mothers to have not completed high school. What is the range of the age of mom's at the time they had their children?\n\n## Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(d$mom_age) # show the minimum and maximum values in mom_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17 29\n```\n:::\n:::\n\n\nThis is a feasible relationship.  American high school finishes at 18 years of age. \n\nBecause we have centred the first variable, it makes sense to centre this variable also.  And, the intercept term would otherwise represent age at 0 years, which also doesn't make sense, right?\n\n## Transform\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$c_mom_age <- d$mom_age - mean(d$mom_age) #\n```\n:::\n\n\nAnd then build a new model by adding it to the previous model formula:\n\n## Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2_c <- lm(kid_score ~ c_mom_hs + c_mom_age, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ c_mom_hs + c_mom_age, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-57.980 -12.545   2.057  14.709  59.325 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  86.7972     0.9532  91.063  < 2e-16 ***\nc_mom_hs     11.3112     2.3783   4.756  2.7e-06 ***\nc_mom_age     0.3261     0.3617   0.902    0.368    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.86 on 431 degrees of freedom\nMultiple R-squared:  0.05791,\tAdjusted R-squared:  0.05353 \nF-statistic: 13.25 on 2 and 431 DF,  p-value: 2.614e-06\n```\n:::\n:::\n\n\nSo for every year that a child's mother is older than the average aged mother, the child's test score is increased by 0.32 of a point. The effect is non-significant (*p* = .368).\n\nI'm betting that `m2` is not a better model than `m1_c` given the weak prediction that `c_mom_age` seems to have on kid's score.\n\nWe check again with a model comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1_c, m2_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ c_mom_hs\nModel 2: kid_score ~ c_mom_hs + c_mom_age\n  Res.Df    RSS Df Sum of Sq     F Pr(>F)\n1    432 170261                          \n2    431 169941  1    320.54 0.813 0.3678\n```\n:::\n:::\n\n\nSo, very quickly we have a demonstration of when a model comparison shows that the more complex model does not do a better job of explaining variance in the outcome variable. With a *p* = .368, we fail to reject a null hypothesis of no difference and the simpler model, `m1_c`, remains the preferred model.\n\nYou probably already knew that by looking at `m2_c`'s $R^2$ value ,(m2_c $R^2$ = 5.8%), but the inferential test makes it official.\n\nAnd, if you think about it - there could be an explanation.  The \"value\" of school to the \"mom\" is in the first variable.  And the lower values of the age range are 17 and 18 - which suggests that there are observations in the data that represent mums who didn't finish school - both variables contain a similar *type* of information.\n\nThe visualisation of the data we did earlier, hints at this; lets repeat this again to have a closer look:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(2:4)], histogram=TRUE, pch=19)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nif we change the code, ever so slightly, we can remove mom's iq from the image so that the information stands out to you:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(2, 4)], histogram=TRUE, pch=19)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n`mom_hs` and `mom_age` at birth have a small correlation of *r* = 0.21. Which tells you that the two variables are measuring a similar construct to a weak extent.\n\nThe astute student is going \"yeah but they're not the variables in the model - we used the centred variables.\"\n\nA quick change from c(2, 4) to c(5, 6) to select the matching columns for those variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(5, 6)], histogram=TRUE, pch=19)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nRemember - centring and standardising your variables does not change the relationships between your variables.  It changes how your model works with the data and makes your model easier to interpret.\n\n## Adding `mom_iq`\n\nLet's add `mom_iq`, because a supporting hypothesis could be that mom's IQ is a hereditary trait?  Or even that given a level of IQ, mom's completion of high school is affected which in turn may predict test scores...\n\n## Transform using a population mean rather than the variable mean\n\n..and again, we can centre the variable.  IQ has a meaningful mean at the population level (100) - so we could use that value to mean centre `mom_iq` (and it just so happens that the mean of the sample is identical: sample mean = 100).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$c_mom_iq <- d$mom_iq - mean(d$mom_iq)\n```\n:::\n\n\n## Model\n\nSo now the intercept reflects the test score for the child at the average level of high school completion, average age and average IQ for the mothers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3_c <- lm(kid_score ~ c_mom_hs + c_mom_age + c_mom_iq, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ c_mom_hs + c_mom_age + c_mom_iq, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-53.289 -12.421   2.399  11.223  50.169 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 86.79724    0.87108  99.643   <2e-16 ***\nc_mom_hs     5.64715    2.25766   2.501   0.0127 *  \nc_mom_age    0.22475    0.33075   0.680   0.4972    \nc_mom_iq     0.56254    0.06065   9.276   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.15 on 430 degrees of freedom\nMultiple R-squared:  0.215,\tAdjusted R-squared:  0.2095 \nF-statistic: 39.25 on 3 and 430 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nWith the addition of the `c_mom_iq`, the model remains significant and a larger amount of variance is explained (21.5%).  `c_mom_iq` is also a significant predictor in the model (t = 9.276, *p* < .001).  It shows a positive relationship with kids score, with every point increase in IQ, a kid's score improves by 0.6 points.  Also, look at what has happened to the other coefficients - reduced in size.  `c_mom_iq`, while having its own independent effect, seems to have an effect upon the other coefficients - suggestive of interactions.\n\n## Model comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1_c, m3_c) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ c_mom_hs\nModel 2: kid_score ~ c_mom_hs + c_mom_age + c_mom_iq\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1    432 170261                                  \n2    430 141605  2     28656 43.509 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nI have performed model comparison using `m1_c` rather than `m2_c`, because the last model comparison showed that `m2_c` was not a better model fit for the data. We could have removed the `c_mom_age` variable, but I had a feasible reason for it to be included, and it feels like *p*-hacking to put it in and then take it out just because it was not significant.\n\nAnyway, `m3_c` is a significantly better fit than `m1_c` (*F*(2, 430) = 43.51, *p* < .001), so we will take this one forward as the new preferred model and introduce an interaction term.  \n\n## Adding an interaction term\nIt felt like a long time getting here - sorry about that, but think about it - the steps along the way have been like setting up your different levels of ANOVA, and that took a couple of weeks too.\n\nFor instance:\n\nM1 = one way ANOVA\nM2 = if you had young and old groups for age, instead of a continuum of age, you would have a two way ANOVA\nM3 = similarly, if you had low and high IQ, instead of a continuum, you would have three factors and a three way ANOVA\n\nHopefully you can see how ANOVA and regression are linked.  Not quite equivalent but linked.\n\nWe will introduce the interaction between the centred variables of `c_mom_hs` and `c_mom_iq`.  We write it like this: `c_mom_hs:c_mom_iq`.  This piece of code is *transforming* two variables into one interaction term in the model.\n\n## Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m4_summary <- summary(m4_c <- lm(kid_score ~ c_mom_hs + \n                                  c_mom_age + \n                                  c_mom_iq + \n                                  c_mom_hs:c_mom_iq, d))) # save the output for use in inline code for the model reporting\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ c_mom_hs + c_mom_age + c_mom_iq + c_mom_hs:c_mom_iq, \n    data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.709 -11.394   1.939  11.268  43.839 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.67680    0.90811  96.549  < 2e-16 ***\nc_mom_hs           2.22584    2.49372   0.893  0.37258    \nc_mom_age          0.35236    0.33008   1.068  0.28634    \nc_mom_iq           0.58735    0.06058   9.695  < 2e-16 ***\nc_mom_hs:c_mom_iq -0.50607    0.16347  -3.096  0.00209 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 429 degrees of freedom\nMultiple R-squared:  0.2321,\tAdjusted R-squared:  0.225 \nF-statistic: 32.42 on 4 and 429 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBefore we interpret anything, lets see if adding the interaction term is justified by performing the model comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m3_c, m4_c) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ c_mom_hs + c_mom_age + c_mom_iq\nModel 2: kid_score ~ c_mom_hs + c_mom_age + c_mom_iq + c_mom_hs:c_mom_iq\n  Res.Df    RSS Df Sum of Sq      F   Pr(>F)   \n1    430 141605                                \n2    429 138511  1    3094.3 9.5838 0.002092 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n`m4_c` has the interaction term as the model with added complexity. The difference between `m3_c` and `m4_c` is significant (F (1, 429) = 9.58, *p* = .002). `m4_c` is the preferred model.  \n\n## Communicate\n\nSo what does the model output say?  Lets reprint the summary to reduce the need for scrolling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = kid_score ~ c_mom_hs + c_mom_age + c_mom_iq + c_mom_hs:c_mom_iq, \n    data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.709 -11.394   1.939  11.268  43.839 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.67680    0.90811  96.549  < 2e-16 ***\nc_mom_hs           2.22584    2.49372   0.893  0.37258    \nc_mom_age          0.35236    0.33008   1.068  0.28634    \nc_mom_iq           0.58735    0.06058   9.695  < 2e-16 ***\nc_mom_hs:c_mom_iq -0.50607    0.16347  -3.096  0.00209 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 429 degrees of freedom\nMultiple R-squared:  0.2321,\tAdjusted R-squared:  0.225 \nF-statistic: 32.42 on 4 and 429 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nLook once more at the coefficients.  `c_mom_hs` is no longer significant; `c_mom_age` remains non-significant, as does `c_mom_iq`, and the new predcitor, the interaction between mother's high school graduation status and IQ is signfificant, showing a negative relationship.  \n\nFrom earlier: When an interaction term is entered into a model and is found to be significant (*p* < .05), this means that the rate of change in the outcome variable changes as the levels in the predictor variables change.  We have to consider the independent effects of the predictors that are in the interaction term and infer whether the interaction effect is a weakening or a strengthening of the outcome variable.\n\nFurther, most of the focus for interpretation will now go onto the interaction term rather than the independent level effects of those predictors. We can no longer, usefully interpret the independent effects of high school graduation status and IQ as independent predictors because their rates of change are NOT uniform across all levels of predictor.\n\nWhen you have performed a model comparison:\n\n  1. Tell your readers which model was preferred first.  \n  2. Then describe the significance of the whole model... \n  3. ...and then describe a range of predictors.  \n  4. Once you have described an individual predictor, interpret it in real terms i.e. what the variables mean:\n  \nIf you present the full model summary in a table, you don't have to interpret all the coefficients in a paragraph.  So here we will just talk about the significant predictors, and imagine that we would be putting the full model summary in a table.\n\nExample:\n\n  1. We built a series of models, with the model containing the interaction term being preferred by model comparison (F(1, 429) = 9.58, *p* = .002).  \n  2. A multiple linear regression with a combination of the mother's high school completion status, age at  child's birth, mother's intelligence score and an interaction between mother's high school completion and mother's intelligence score was a significant model (F (4, 429) = 32.42, *p* < .001) and explained 23.2% of the variance in kids' test scores.\n  3. Neither high school completion status nor mother's age at the child's birth was significant (*p* = 0.373 and *p* = 0.286).  Mother's intelligence was significant (t = 9.7, *p* < .001) and so was the interaction term between high school completion status and mother's intelligence (t = -3.1, *p* = .002).\n  4. The relationship between test scores and mother's high school graduation status and test scores and mothers IQ is positive, suggesting that high school graduation status means that test scores are higher on average he positive relationship that we see between test scores and mother's intelligence predicts that for each point increase in IQ, the test score for a child who's mother did not complete school increases by 0.59 of a test point. And while having a mother that completed high school increases test scores by 2.23 points,  the negative direction of the interaction between high school successfully completed and a point increase in IQ actually weakens the strength of this effect by 0.51. \n  \n### Model diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2)) # display plots in a 2 x 2 panel\nplot(m4_c)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nphew! looks a little healthier than the last dataset analysis!\n\n### A possible reporting and interpretation of the model\n\nOur multiple regression modelled 3-year-old test scores as a function of whether their mothers completed high school, the mother's age at the child's birth and their IQ score.  We also included an interaction term for the relationship between high school completion and IQ score.  We tentatively framed feasible research questions and built a series of models, using model comparison to select models to carry forward. All variables were centred before being entered into the model.\n\nThe full model with all independent predictors plus the interaction term was significant ($F{_(}{_4}{_,}{_4}{_2}{_9}{_)}$ = 32.42, *p* < 0.001). and the best model of the four completed (*p* = .002). This set of predictors explains 23.21% of the variance in child test scores.  While the status of the mother's high school completion status was not significant (mom_hs: *t* = 0.89, *p* = 0.373), the mother's IQ score was (mom_iq: *t* = 9.7, *p* < .001).  This showed a positive relationship with the child test scores, indicating that as the mother's IQ increased, so to did the test scores. The interaction however, showed a negative relationship which indicated that this increase was shallower for those children whose mother had completed high school (hs x iq interaction: *t* = -3.1, *p* = 0.002).\n\nWe inspected diagnostic plots which show reasonable dispersion of residuals.  There are a number of points that could be influential or show high leverage however they don't appear to be aberrant.\n\n\n### Plotting the raw values to show the interaction\n\nThis is the same code and plot as we started with at the top of the script.  Repeated here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4_raw <- lm(kid_score ~ mom_hs + mom_age + mom_iq + mom_hs:mom_iq, d)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(d, aes(mom_iq, kid_score)) +\n  geom_point(aes(color = factor(mom_hs)), show.legend = FALSE) +\n  geom_abline(\n    intercept = c(coef(m4_raw)[1], sum(coef(m4_raw)[1:2])),\n    slope = c(coef(m4_raw)[4], sum(coef(m4_raw)[4:5])),\n    color = c(\"black\", \"grey\")) +\n  scale_color_manual(values = c(\"black\", \"grey\")) +\n  labs(x = \"Mother IQ Score\", y = \"Child Test Score\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n### Plotting the fitted model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(d, aes(c_mom_iq, kid_score)) +\n  geom_point(aes(color = factor(c_mom_hs)), show.legend = FALSE) +\n  geom_abline(\n    intercept = c(coef(m4_c)[1], sum(coef(m4_c)[1:2])),\n    slope = c(coef(m4_c)[4], sum(coef(m4_c)[4:5])),\n    color = c(\"black\", \"grey\")) +\n  scale_color_manual(values = c(\"black\", \"grey\")) +\n  labs(x = \"Mother IQ score\", y = \"Child test score\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nI've taken this code from the website from which the data was retrieved - it is a much cleaner plot and great code! I have adapted the code to fit the model fitted and the raw data above and plotted two versions to demonstrate that the transformations do not change the information about the comparisons / effects within the model - only the scale of measurement as observed on the plot axes.\n\nThe grey circles represent the group of children whose mothers completed high school (HS) while the black circles represent the group of children whose mothers did not complete high school (no HS).  The interaction indicates that while the mother's IQ score is below a score of approximately 105, the no HS child test scores are lower than the HS child test scores, however rising above approximately 105 IQ points, the no HS child test scores are higher than the HS child test scores.  One interpretation could be that having an above average IQ score, in the context of not completing high school is a protective factor for an offspring's attainment at the age of 3!\n\nHow are we doing in our list of things to think about - We need to look at:\n\n  - a model with some significant predictors! - done\n  - correlation matrices - done\n  - centering predictors - done\n  - standardising predictors - done\n  - models with categorical predictors - done & ongoing\n    - interpreting models with categorical predictors - done & ongoing\n  - models with interaction terms - done\n  - the properties of multicollinearity\n  - choosing between different models - done\n  - reporting models - ongoing\n\n\n# Lab Task\n\nUpload [this zip file](data/Wk3/Lab_3_Materials.zip) to the R server, and complete the `Multiple_Regression_Interactions_Student.Rmd` file using the data included in the zip file.\n\nThe model output you are aiming to match is below\n\n![Model output](Images/Wk3/Model Output.png)\n\n# Submit Scripts\n\nRemember to submit your group scripts if you want to receive and see feedback on your own and other groups' scripts.",
    "supporting": [
      "Week3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/grViz-binding-1.0.9/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}